function Manifest = download_europe_long_routes(outputFolder)
%DOWNLOAD_EUROPE_LONG_ROUTES Retrieve reproducible OSRM/OSM coach corridors.
% The saved JSON files contain the complete OSRM distance, duration, and
% speed annotations used by convert_osrm_coach_route. Run this function only
% when intentionally refreshing the bundled source snapshot.
arguments
    outputFolder (1,1) string = fullfile(fileparts(mfilename('fullpath')), ...
        "documentation","reference_routes","osrm")
end
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

routeID = ["EUR-BER-VIE";"EUR-HAM-PAR";"EUR-MUC-ROM";"EUR-AMS-ZRH"; ...
    "EUR-STO-CPH";"EUR-PRG-BRU";"EUR-WAW-PRG";"EUR-FRA-MIL"];
routeName = ["Berlin, Germany to Vienna, Austria"; ...
    "Hamburg, Germany to Paris, France"; ...
    "Munich, Germany to Rome, Italy"; ...
    "Amsterdam, Netherlands to Zurich, Switzerland"; ...
    "Stockholm, Sweden to Copenhagen, Denmark"; ...
    "Prague, Czechia to Brussels, Belgium"; ...
    "Warsaw, Poland to Prague, Czechia"; ...
    "Frankfurt, Germany to Milan, Italy"];
region = ["Germany / Austria";"Germany / France";"Germany / Austria / Italy"; ...
    "Netherlands / Germany / Switzerland";"Sweden / Denmark"; ...
    "Czechia / Germany / Belgium";"Poland / Czechia"; ...
    "Germany / Switzerland / Italy"];
originLongitude = [13.4050;9.9937;11.5820;4.9041;18.0686;14.4378;21.0122;8.6821];
originLatitude = [52.5200;53.5511;48.1351;52.3676;59.3293;50.0755;52.2297;50.1109];
destinationLongitude = [16.3738;2.3522;12.4964;8.5417;12.5683;4.3517;14.4378;9.1900];
destinationLatitude = [48.2082;48.8566;41.9028;47.3769;55.6761;50.8503;50.0755;45.4642];
fileName = ["OSRM_Berlin_Vienna.json";"OSRM_Hamburg_Paris.json"; ...
    "OSRM_Munich_Rome.json";"OSRM_Amsterdam_Zurich.json"; ...
    "OSRM_Stockholm_Copenhagen.json";"OSRM_Prague_Brussels.json"; ...
    "OSRM_Warsaw_Prague.json";"OSRM_Frankfurt_Milan.json"];

distanceKm = zeros(numel(routeID),1);
drivingDurationHours = zeros(numel(routeID),1);
retrievedUTC = strings(numel(routeID),1);
options = weboptions('Timeout',120,'ContentType','json', ...
    'HeaderFields',{'User-Agent','HybridBusProject/1.3 route research'});
for index = 1:numel(routeID)
    coordinates = sprintf('%.4f,%.4f;%.4f,%.4f',originLongitude(index), ...
        originLatitude(index),destinationLongitude(index),destinationLatitude(index));
    queryURL = "https://router.project-osrm.org/route/v1/driving/"+coordinates+ ...
        "?overview=full&geometries=geojson&steps=false&annotations=distance,duration,speed";
    response = webread(queryURL,options);
    assert(string(response.code)=="Ok" && ~isempty(response.routes), ...
        'HybridBus:OSRMDownload','OSRM did not return a route for %s.',routeID(index));
    retrievedUTC(index) = string(datetime('now','TimeZone','UTC', ...
        'Format','yyyy-MM-dd''T''HH:mm:ssXXX'));
    assert(isfield(response.routes(1),'geometry') && ...
        size(response.routes(1).geometry.coordinates,1)>=2, ...
        'HybridBus:OSRMDownload','OSRM did not return GeoJSON geometry for %s.',routeID(index));
    payload = struct('RouteID',routeID(index),'RouteName',routeName(index), ...
        'Region',region(index),'OriginLongitude',originLongitude(index), ...
        'OriginLatitude',originLatitude(index), ...
        'DestinationLongitude',destinationLongitude(index), ...
        'DestinationLatitude',destinationLatitude(index), ...
        'RetrievedUTC',retrievedUTC(index),'QueryURL',queryURL, ...
        'Attribution',"© OpenStreetMap contributors", ...
        'License',"Open Data Commons Open Database License (ODbL) 1.0", ...
        'OSRMResponse',response);
    encoded = jsonencode(payload,'PrettyPrint',true);
    targetFile = fullfile(outputFolder,fileName(index));
    fileID = fopen(targetFile,'w','n','UTF-8');
    assert(fileID>=0,'HybridBus:RouteWrite','Cannot create %s.',targetFile);
    cleanup = onCleanup(@()fclose(fileID));
    fwrite(fileID,encoded,'char');
    clear cleanup
    distanceKm(index) = response.routes(1).distance/1000;
    drivingDurationHours(index) = response.routes(1).duration/3600;
end
Manifest = table(routeID,routeName,region,fileName,distanceKm,drivingDurationHours, ...
    retrievedUTC,originLongitude,originLatitude,destinationLongitude, ...
    destinationLatitude);
writetable(Manifest,fullfile(outputFolder,'OSRM_Route_Manifest.csv'));
end
