classdef optimizationWorkflowTest < matlab.unittest.TestCase
    %OPTIMIZATIONWORKFLOWTEST Regression tests for app-shaped bounded searches.

    properties
        DatabaseFile string
        Database struct
    end

    methods (TestClassSetup)
        function configureProject(testCase)
            ProjectFolder=fileparts(fileparts(mfilename('fullpath')));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(ProjectFolder,"src")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture( ...
                fullfile(ProjectFolder,"models")));
            testCase.DatabaseFile=fullfile(ProjectFolder,"data", ...
                "HybridBus_ComponentDatabase.xlsx");
            testCase.Database=load_hybrid_bus_database(testCase.DatabaseFile);
        end
    end

    methods (Test)
        function defaultHybridStartsFromDisplayedConfiguration(testCase)
            overrides=appShapedOverrides(testCase.Database,"Hybrid",1);
            result=optimize_hybrid_bus_configuration(testCase.DatabaseFile, ...
                Vary=["Battery1","Motor","Genset","FinalDrive"], ...
                MaxConfigurations=1,BaseOverrides=overrides,SaveResults=false);

            first=result.EvaluatedConfigurations(1,:);
            testCase.verifyEqual(first.FinalDriveID,string(testCase.Database.Dashboard.SelectedFinalDrive));
            testCase.verifyTrue(first.Feasible);
            testCase.verifyNotEmpty(result.BestResult);
        end

        function optimizerCarriesEditableLoadIntoCandidateMass(testCase)
            overrides=appShapedOverrides(testCase.Database,"Hybrid",1);
            overrides.LoadMass_t=4.25;
            expectedInput=prepare_hybrid_bus_inputs(testCase.Database,overrides);
            result=optimize_hybrid_bus_configuration(testCase.DatabaseFile, ...
                Vary="Motor",MaxConfigurations=1,BaseOverrides=overrides,SaveResults=false);

            first=result.EvaluatedConfigurations(1,:);
            testCase.verifyEqual(first.EstimatedVehicleMass_kg, ...
                expectedInput.Mass.TotalVehicleMass_kg,'AbsTol',1e-9);
            testCase.verifyEqual(expectedInput.Mass.TotalVehicleMass_kg- ...
                expectedInput.Mass.CurbMass_kg,4250,'AbsTol',1e-9);
        end

        function defaultBEVStartsFromDisplayedConfiguration(testCase)
            overrides=appShapedOverrides(testCase.Database,"BEV",1);
            result=optimize_hybrid_bus_configuration(testCase.DatabaseFile, ...
                Vary=["Battery1","Battery2","Motor","FinalDrive"], ...
                MaxConfigurations=1,BaseOverrides=overrides,SaveResults=false);

            first=result.EvaluatedConfigurations(1,:);
            testCase.verifyEqual(first.FinalDriveID,string(testCase.Database.Dashboard.SelectedFinalDrive));
            testCase.verifyTrue(first.Feasible);
            testCase.verifyEqual(result.BestResult.Summary.PowertrainMode,'BEV');
        end

        function rankingIsAscendingAndFeasible(testCase)
            overrides=appShapedOverrides(testCase.Database,"Hybrid",1);
            result=optimize_hybrid_bus_configuration(testCase.DatabaseFile, ...
                Vary="Motor",MaxConfigurations=4,BaseOverrides=overrides,SaveResults=false);

            costs=result.TopConfigurations.CostPer_km;
            testCase.verifyNotEmpty(costs);
            testCase.verifyTrue(issorted(costs));
            testCase.verifyTrue(all(result.TopConfigurations.Feasible));
        end
    end
end

function overrides=appShapedOverrides(database,powertrainMode,batterySetMultiplier)
D=database.Dashboard;
overrides=struct('SelectedRoute',string(D.SelectedRoute), ...
    'SelectedBattery1',string(D.SelectedBattery1), ...
    'SelectedBattery2',string(D.SelectedBattery2), ...
    'SelectedMotor',string(D.SelectedMotor), ...
    'SelectedGenset',string(D.SelectedGenset), ...
    'SelectedTyre',string(D.SelectedTyre), ...
    'SelectedFinalDrive',string(D.SelectedFinalDrive), ...
    'SelectedMass',string(D.SelectedMass), ...
    'SelectedAuxProfile',string(D.SelectedAuxProfile), ...
    'SelectedEnvironment',string(D.SelectedEnvironment), ...
    'SelectedControl',string(D.SelectedControl), ...
    'InitialBattery1SOE',double(D.InitialBattery1SOE), ...
    'InitialBattery2SOE',double(D.InitialBattery2SOE), ...
    'InitialActiveBattery',double(D.InitialActiveBattery), ...
    'AuxiliaryScalarOverride',double(D.AuxiliaryScalarOverride), ...
    'FuelTankCapacity',double(D.FuelTankCapacity), ...
    'FuelPrice',double(D.FuelPrice), ...
    'ElectricityPrice',double(D.ElectricityPrice), ...
    'RepeatUntilDepleted',false, ...
    'PowertrainMode',string(powertrainMode), ...
    'BatterySetMultiplier',double(batterySetMultiplier));
if isfield(D,'LoadMass_t'), overrides.LoadMass_t=double(D.LoadMass_t);
else, overrides.LoadMass_t=0; end
if strcmpi(powertrainMode,"BEV")
    overrides.InitialBattery1SOE=0.85;
    overrides.InitialBattery2SOE=0.85;
end
end
