function runtime = architecture_component_runtime_data(result,componentKey)
%ARCHITECTURE_COMPONENT_RUNTIME_DATA Component KPIs and logged signals.
%   RUNTIME = ARCHITECTURE_COMPONENT_RUNTIME_DATA(RESULT,COMPONENTKEY)
%   derives component-specific evidence from one completed simulation. It
%   reports logged signals and explicitly labelled first-principles derived
%   quantities that are present in the concept-level result structure.

arguments
    result
    componentKey (1,1) string
end

initialSignalGroups=emptySignalGroups();
runtime=struct('HasResult',~isempty(result),'ComponentKey',lower(componentKey), ...
    'ScopeText',"No simulation result is available.", ...
    'KPIRows',{{'Simulation status','Run required','','Run a manual case or optimization first.'}}, ...
    'SignalGroups',initialSignalGroups, ...
    'SignalOptions',initialSignalGroups, ...
    'SignalNote',"Run a simulation to view physical signals for this component.");
if isempty(result)
    return
end

S=result.Signals; Q=result.Summary; I=result.InputParameters;
t=result.Time(:); dt=timeStep(t);
integrate=@(power)sum(power(:).*dt)/3600;
runtime.ScopeText=scopeText(result);
runtime.SignalNote="Signals are taken from the app's currently displayed result. Time is shown in minutes or hours according to mission duration.";
key=lower(componentKey);

switch key
    case {"battery1","battery2"}
        if key=="battery1"
            battery=S.Battery1; other=S.Battery2; batteryInput=I.Battery1;
            baseBattery=I.BaseBattery1;
            finalSOE=Q.FinalBattery1SOE; packCount=Q.Battery1PackCount; label="Battery 1";
        else
            battery=S.Battery2; other=S.Battery1; batteryInput=I.Battery2;
            baseBattery=I.BaseBattery2;
            finalSOE=Q.FinalBattery2SOE; packCount=Q.Battery2PackCount; label="Battery 2";
        end
        power=battery.Power_kW(:); otherPower=other.Power_kW(:);
        share=abs(power)./max(abs(power)+abs(otherPower),eps);
        allocatedLoss=S.Energy.BatteryLoss_kW(:).*share;
        connectionStatus="Installed / role-managed";
        if strcmpi(Q.PowertrainMode,'BEV') && packCount==0
            connectionStatus="Disconnected in this BEV configuration";
        end
        runtime.KPIRows={ ...
            'Connection status',char(connectionStatus),'',sprintf('%d installed pack(s)',packCount); ...
            'Energy throughput',formatNumber(integrate(abs(power)),3),'kWh','Integral of absolute terminal power'; ...
            'Discharge energy',formatNumber(integrate(max(power,0)),3),'kWh','Positive battery power'; ...
            'Charge energy',formatNumber(integrate(max(-power,0)),3),'kWh','Regeneration or genset charging'; ...
            'Allocated battery loss',formatNumber(integrate(allocatedLoss),3),'kWh','Combined logged battery loss allocated by absolute-power share'; ...
            'Peak discharge power',formatNumber(max(power),2),'kW','Maximum positive terminal power'; ...
            'Peak charge power',formatNumber(max(-power),2),'kW','Maximum charging magnitude'; ...
            'Final SOE',formatNumber(100*finalSOE,1),'%','Stored energy divided by usable energy'; ...
            'Observed SOE range',sprintf('%.1f to %.1f',100*min(battery.SOE),100*max(battery.SOE)),'%','Simulation history'; ...
            'Installed usable energy',formatNumber(batteryInput.UsableEnergy_kWh,1),'kWh','Scaled by installed parallel-pack count'; ...
            'Usable energy per pack',formatNumber(baseBattery.UsableEnergy_kWh,1),'kWh','Unscaled database specification'; ...
            'Peak discharge current',formatNumber(max(battery.Current_A),1),'A','Positive terminal-current convention'; ...
            'Peak charge current',formatNumber(max(-battery.Current_A),1),'A','Negative terminal-current magnitude'};
        runtime.KPIRows=[runtime.KPIRows; { ...
            'Battery temperature',formatNumber(battery.Temperature_C(1),1),'degC','Ambient-temperature proxy used by concept maps'; ...
            'Observed resistance range',sprintf('%.4f to %.4f',min(battery.InternalResistance_Ohm),max(battery.InternalResistance_Ohm)),'ohm','SOE/temperature lookup result'; ...
            'Ohmic loss energy',formatNumber(integrate(battery.OhmicLoss_kW),3),'kWh','Integral of I^2R loss estimate'}];
        runtime.SignalGroups=[ ...
            signalGroup(label+" terminal power",'Power (kW)',label+" power",power), ...
            signalGroup(label+" state of energy",'SOE (%)',label+" SOE",100*battery.SOE(:)), ...
            signalGroup(label+" terminal voltage estimate",'Voltage (V)', ...
                label+" voltage",battery.Voltage_V(:)), ...
            signalGroup(label+" terminal current estimate",'Current (A)', ...
                label+" current",battery.Current_A(:)), ...
            signalGroup(label+" instantaneous current limits",'Current limit (A)', ...
                ["Discharge limit","Charge limit"], ...
                [battery.DischargeCurrentLimit_A(:) battery.ChargeCurrentLimit_A(:)]), ...
            signalGroup(label+" derived terminal power capability",'Power capability (kW)', ...
                ["Discharge capability","Charge capability"], ...
                [battery.DerivedDischargePowerCapability_kW(:) ...
                battery.DerivedChargePowerCapability_kW(:)]), ...
            signalGroup(label+" internal resistance",'Resistance (ohm)', ...
                "Internal resistance",battery.InternalResistance_Ohm(:)), ...
            signalGroup(label+" ohmic loss",'Power loss (kW)', ...
                "I^2R loss",battery.OhmicLoss_kW(:)), ...
            signalGroup(label+" temperature",'Temperature (degC)', ...
                "Battery temperature",battery.Temperature_C(:))];
        runtime.SignalNote=runtime.SignalNote+" Current limits, open-circuit voltage, and resistance use bilinear SOE/temperature maps. Terminal power capability is derived from current, OCV, resistance, voltage headroom, and available energy. Battery temperature is the selected ambient value; no thermal state model is claimed.";

    case "motors"
        motorDC=S.Motors.ElectricalPower_kW(:);
        motorMechanical=motorMechanicalPower(result);
        conversionLoss=S.Motors.LossPower_kW(:);
        runtime.KPIRows={ ...
            'Electrical energy throughput',formatNumber(integrate(abs(motorDC)),3),'kWh','Absolute motor-inverter DC energy'; ...
            'Motoring electrical energy',formatNumber(integrate(max(motorDC,0)),3),'kWh','Positive DC power'; ...
            'Regenerative DC energy',formatNumber(integrate(max(-motorDC,0)),3),'kWh','Negative DC power magnitude'; ...
            'Mechanical energy throughput',formatNumber(integrate(abs(motorMechanical)),3),'kWh','Derived at the motor shaft'; ...
            'Mapped motor-loss energy',formatNumber(integrate(conversionLoss),3),'kWh','Torque-speed loss-map integration for the motor pair'; ...
            'Peak mapped motor loss',formatNumber(max(conversionLoss),2),'kW','Combined loss of both motors'; ...
            'Peak motoring DC power',formatNumber(max(motorDC),2),'kW','Motor-pair electrical input'; ...
            'Peak regenerative DC power',formatNumber(max(-motorDC),2),'kW','Motor-pair electrical return'; ...
            'Maximum motor speed',formatNumber(max(S.Motors.MotorSpeed_rpm),0),'rpm','Logged motor speed'};
        runtime.SignalGroups=[ ...
            signalGroup('Motor-inverter power flow','Power (kW)', ...
                ["Electrical DC","Mechanical shaft"],[motorDC motorMechanical]), ...
            signalGroup('Motor speed','Speed (rpm)',"Motor speed",S.Motors.MotorSpeed_rpm(:)), ...
            signalGroup('Motor torque','Torque (N m)', ...
                ["Motor pair","Per motor"],[S.Motors.PairTorque_Nm(:) S.Motors.PerMotorTorque_Nm(:)]), ...
            signalGroup('Motor dynamic power limits','Mechanical power limit (kW)', ...
                ["Driving","Regeneration"], ...
                [S.Motors.DrivingPowerLimit_kW(:) S.Motors.RegenerationPowerLimit_kW(:)]), ...
            signalGroup('Motor torque-speed mapped loss','Power loss (kW)', ...
                "Motor pair loss",S.Motors.LossPower_kW(:))];

    case "reduction"
        wheelPower=S.Wheel.Delivered_kW(:); motorMechanical=motorMechanicalPower(result);
        drivelineLoss=abs(motorMechanical-wheelPower);
        tyreRadius=max(I.Tyre.LoadedRadius_m,eps);
        wheelSpeed=S.Vehicle.Speed_m_s(:)/tyreRadius;
        wheelTorque=zeros(size(wheelSpeed)); moving=abs(wheelSpeed)>1e-9;
        wheelTorque(moving)=1000*wheelPower(moving)./wheelSpeed(moving);
        runtime.KPIRows={ ...
            'Wheel-side energy throughput',formatNumber(integrate(abs(wheelPower)),3),'kWh','Absolute delivered wheel energy'; ...
            'Driveline-loss estimate',formatNumber(integrate(drivelineLoss),3),'kWh','Directional-efficiency difference'; ...
            'Peak traction wheel power',formatNumber(max(wheelPower),2),'kW','Positive delivered power'; ...
            'Peak regenerative wheel power',formatNumber(max(-wheelPower),2),'kW','Negative delivered power magnitude'; ...
            'Peak wheel torque magnitude',formatNumber(max(abs(wheelTorque)),0),'N m','Derived from delivered wheel power and speed'; ...
            'Final-drive ratio',formatNumber(I.FinalDrive.Ratio,3),'-','Database specification'};
        runtime.SignalGroups=[ ...
            signalGroup('Fixed-reduction power','Power (kW)', ...
                ["Motor shaft","Wheel delivered"],[motorMechanical wheelPower]), ...
            signalGroup('Wheel torque','Torque (N m)',"Wheel torque",wheelTorque)];

    case {"engine","generator"}
        electrical=S.Genset.ElectricalPower_kW(:); mechanical=S.Genset.MechanicalPower_kW(:);
        loss=max(0,mechanical-electrical); fuelRate=3600*S.Genset.FuelRate_L_s(:);
        conversionEfficiency=sum(electrical.*dt)/max(sum(mechanical.*dt),eps)*100;
        if key=="engine", titlePrefix='Engine'; primaryEnergy=integrate(mechanical);
        else, titlePrefix='Generator'; primaryEnergy=integrate(electrical); end
        runtime.KPIRows={ ...
            [titlePrefix ' mission energy'],formatNumber(primaryEnergy,3),'kWh','Integrated power over the displayed result'; ...
            'Mechanical input energy',formatNumber(integrate(mechanical),3),'kWh','Engine shaft energy'; ...
            'Electrical output energy',formatNumber(integrate(electrical),3),'kWh','Isolated standby-charger output'; ...
            'Generator conversion loss',formatNumber(integrate(loss),3),'kWh','Mechanical minus electrical energy'; ...
            'Generator efficiency proxy',formatNumber(conversionEfficiency,1),'%','Mission-integrated electrical/mechanical ratio'; ...
            'Fuel consumed',formatNumber(Q.Fuel_L,2),'L','Integrated fuel-rate signal'; ...
            'Runtime',formatNumber(Q.GensetRuntime_s/60,1),'min','Time at the fixed operating point'; ...
            'Starts',formatNumber(Q.GensetStarts,0),'count','Off-to-on events'};
        runtime.SignalGroups=[ ...
            signalGroup(titlePrefix+" power",'Power (kW)', ...
                ["Mechanical","Electrical"],[mechanical electrical]), ...
            signalGroup('Fuel rate','Fuel rate (L/h)',"Fuel rate",fuelRate)];

    case "fuel"
        fuelRate=3600*S.Genset.FuelRate_L_s(:);
        cumulativeFuel=cumsum(S.Genset.FuelRate_L_s(:).*dt);
        tankCapacity=I.Vehicle.FuelTank_L;
        runtime.KPIRows={ ...
            'Fuel consumed',formatNumber(Q.Fuel_L,2),'L','Integrated fuel-rate signal'; ...
            'Tank capacity',formatNumber(tankCapacity,1),'L','Configured usable tank volume'; ...
            'Fuel remaining',formatNumber(max(0,tankCapacity-Q.Fuel_L),2),'L','Tank capacity minus consumed fuel'; ...
            'Peak fuel rate',formatNumber(max(fuelRate),2),'L/h','Maximum instantaneous rate'; ...
            'Average fuel rate while running',formatNumber(meanPositive(fuelRate),2),'L/h','Mean of positive samples'; ...
            'Genset runtime',formatNumber(Q.GensetRuntime_s/60,1),'min','Fuel-consuming operating time'};
        runtime.SignalGroups=[ ...
            signalGroup('Fuel-flow rate','Fuel rate (L/h)',"Fuel rate",fuelRate), ...
            signalGroup('Cumulative fuel use','Fuel used (L)',"Cumulative fuel",cumulativeFuel)];

    case "auxiliary"
        power=S.Auxiliary.Power_kW(:);
        runtime.KPIRows={ ...
            'Auxiliary energy',formatNumber(Q.AuxiliaryEnergy_kWh,3),'kWh','Base and route-scaled hotel/HVAC load'; ...
            'Regeneration supplied to auxiliaries',formatNumber(Q.RegenerationToAuxiliaryEnergy_kWh,3),'kWh','First-priority regenerative allocation'; ...
            'Peak auxiliary power',formatNumber(max(power),2),'kW','Maximum electrical demand'; ...
            'Mean auxiliary power',formatNumber(mean(power),2),'kW','Time-average electrical demand'; ...
            'Regeneration coverage',formatNumber(100*Q.RegenerationToAuxiliaryEnergy_kWh/max(Q.AuxiliaryEnergy_kWh,eps),1),'%','Share of auxiliary energy supplied by regeneration'};
        runtime.SignalGroups=[ ...
            signalGroup('DC auxiliary demand','Power (kW)',"Auxiliary power",power), ...
            signalGroup('Cumulative auxiliary energy','Energy (kWh)',"Auxiliary energy",cumsum(power.*dt)/3600)];

    case "friction_brake"
        brakingDemand=S.Wheel.BrakingDemand_kW(:);
        regenerative=S.Wheel.RegenerativeBraking_kW(:);
        friction=S.Wheel.FrictionBrakePower_kW(:);
        unmet=S.Wheel.UnmetBraking_kW(:);
        runtime.KPIRows={ ...
            'Pneumatic braking energy',formatNumber(Q.FrictionBrakeEnergy_kWh,3),'kWh','Wheel energy converted to friction heat'; ...
            'Peak pneumatic braking power',formatNumber(max(friction),2),'kW','Maximum residual braking demand'; ...
            'Active duration',formatNumber(sum(dt(friction>1e-6)),1),'s','Time with nonzero friction braking'; ...
            'Share of wheel-braking energy',formatNumber(100*Q.FrictionBrakeEnergy_kWh/max(Q.WheelBrakingDemandEnergy_kWh,eps),1),'%','Pneumatic share of requested wheel braking'; ...
            'Regenerative wheel-braking energy',formatNumber(Q.RegenerativeWheelBrakingEnergy_kWh,3),'kWh','First-priority braking contribution'; ...
            'Unmet braking energy',formatNumber(Q.UnmetBrakingEnergy_kWh,6),'kWh','Zero for the ideal residual actuator'};
        runtime.SignalGroups=[ ...
            signalGroup('Blended wheel braking','Braking power magnitude (kW)', ...
                ["Demand","Regenerative","Pneumatic friction","Unmet"], ...
                [brakingDemand regenerative friction unmet]), ...
            signalGroup('Cumulative braking energy','Energy (kWh)', ...
                ["Demand","Regenerative","Pneumatic friction"], ...
                [cumsum(brakingDemand.*dt) cumsum(regenerative.*dt) ...
                cumsum(friction.*dt)]/3600)];

    case {"resistor","charger"}
        if key=="resistor"
            power=S.Regeneration.ResistorLoadBank_kW(:);
            runtime.KPIRows={ ...
                'Dissipated regenerative energy',formatNumber(Q.ResistorLoadBankEnergy_kWh,3),'kWh','Third-priority regenerative destination'; ...
                'Peak load-bank power',formatNumber(max(power),2),'kW','Maximum controlled waste-heat power'; ...
                'Active duration',formatNumber(sum(dt(power>1e-6)),1),'s','Time with nonzero dissipation'; ...
                'Share of available regeneration',formatNumber(100*Q.ResistorLoadBankEnergy_kWh/max(Q.RegeneratedEnergy_kWh,eps),1),'%','Surplus after auxiliary and active-battery limits'};
            runtime.SignalGroups=[ ...
                signalGroup('Resistor load-bank power','Power (kW)',"Load-bank power",power), ...
                signalGroup('Cumulative dissipated energy','Energy (kWh)',"Dissipated energy",cumsum(power.*dt)/3600)];
        else
            power=S.Genset.ElectricalPower_kW(:);
            runtime.KPIRows={ ...
                'Charged electrical energy',formatNumber(Q.GensetElectricalEnergy_kWh,3),'kWh','Fixed-point output to the standby battery'; ...
                'Peak charger output',formatNumber(max(power),2),'kW','Maximum logged DC charging power'; ...
                'Active duration',formatNumber(sum(dt(power>1e-6))/60,1),'min','Time with nonzero charger output'; ...
                'Genset starts',formatNumber(Q.GensetStarts,0),'count','Charging-session start events'; ...
                'Charger voltage/current','NOT AVAILABLE','','The concept model logs power but not electrical terminal voltage or current'};
            runtime.SignalGroups=[ ...
                signalGroup('Fixed-point charger output','Power (kW)',"Charger output",power), ...
                signalGroup('Cumulative standby-charge energy','Energy (kWh)', ...
                    "Delivered charge energy",cumsum(power.*dt)/3600)];
        end

    case {"grid_charger"}
        runtime=externalChargerRuntime(runtime,result);

    case {"controller","bev_controller","active_selector","standby_selector"}
        active=S.Controller.ActiveBattery(:); standby=S.Controller.StandbyBattery(:);
        switches=sum(abs(diff(active))>0);
        duty1=100*sum(dt(active==1))/max(sum(dt),eps);
        duty2=100*sum(dt(active==2))/max(sum(dt),eps);
        runtime.KPIRows={ ...
            'Powertrain mode',char(string(Q.PowertrainMode)),'','Displayed simulation result'; ...
            'Battery-role switches',formatNumber(switches,0),'count','Changes in active battery index'; ...
            'Battery 1 active duty',formatNumber(duty1,1),'%','Fraction of simulated time'; ...
            'Battery 2 active duty',formatNumber(duty2,1),'%','Fraction of simulated time'; ...
            'Connected battery count',formatNumber(Q.ConnectedBatteryCount,0),'packs','Traction-connected count at the terminal sample'; ...
            'Genset starts',formatNumber(Q.GensetStarts,0),'count','Standby-charging state transitions'; ...
            'Energy-balance error',formatNumber(Q.EnergyBalanceError_kWh,6),'kWh','System conservation diagnostic'};
        runtime.SignalGroups=[ ...
            signalGroup('Battery role selection','Battery index', ...
                ["Active","Standby"],[active standby]), ...
            signalGroup('Supervisory operating mode','Mode index',"Operating mode",S.Controller.Mode(:))];

    case "traction_bus"
        p1=S.Battery1.Power_kW(:); p2=S.Battery2.Power_kW(:);
        motor=S.Motors.ElectricalPower_kW(:); auxiliary=S.Auxiliary.Power_kW(:);
        runtime.KPIRows={ ...
            'Motor DC energy throughput',formatNumber(integrate(abs(motor)),3),'kWh','Traction and regeneration'; ...
            'Auxiliary energy',formatNumber(Q.AuxiliaryEnergy_kWh,3),'kWh','Always-on DC demand'; ...
            'Battery energy throughput',formatNumber(Q.BatteryThroughput_kWh,3),'kWh','Both battery terminals'; ...
            'Unmet DC/traction energy',formatNumber(Q.UnmetTractionEnergy_kWh,6),'kWh','Source/capability shortfall'; ...
            'Energy-balance error',formatNumber(Q.EnergyBalanceError_kWh,6),'kWh','Conservation diagnostic'; ...
            'Peak motor DC demand',formatNumber(max(motor),2),'kW','Positive traction power'};
        runtime.SignalGroups=[ ...
            signalGroup('Traction DC-bus power','Power (kW)', ...
                ["Battery 1","Battery 2","Motor DC","Auxiliary"],[p1 p2 motor auxiliary]), ...
            signalGroup('DC-bus diagnostics','Power (kW)', ...
                ["Balance residual","Unmet DC"],[S.Energy.BalanceResidual_kW(:) S.Energy.UnmetDCPower_kW(:)]), ...
            signalGroup('DC-bus voltage','Voltage (V)',"DC-bus voltage",S.DCBus.Voltage_V(:)), ...
            signalGroup('DC-bus current','Current (A)',"DC-bus current",S.DCBus.Current_A(:))];
        runtime.SignalNote=runtime.SignalNote+" DC-bus voltage is the selected motor voltage-class nominal value; current is reconstructed from signed net bus power.";

    case "vehicle"
        speed=3.6*S.Vehicle.Speed_m_s(:); acceleration=S.Vehicle.Acceleration_m_s2(:);
        moving=speed>0.1;
        averageMoving=0; if any(moving), averageMoving=mean(speed(moving)); end
        runtime.KPIRows={ ...
            'Mission distance',formatNumber(Q.RouteDistance_km,2),'km','Achieved distance in the displayed result'; ...
            'Maximum speed',formatNumber(max(speed),1),'km/h','Prescribed route speed'; ...
            'Average moving speed',formatNumber(averageMoving,1),'km/h','Excludes stops below 0.1 km/h'; ...
            'Maximum acceleration',formatNumber(max(acceleration),2),'m/s^2','Filtered longitudinal acceleration'; ...
            'Maximum deceleration',formatNumber(min(acceleration),2),'m/s^2','Most negative filtered acceleration'; ...
            'Peak wheel demand',formatNumber(max(S.Wheel.Demand_kW),2),'kW','Positive tractive wheel power'; ...
            'Regenerative wheel demand',formatNumber(max(-S.Wheel.Demand_kW),2),'kW','Braking power magnitude'; ...
            'Pneumatic braking energy',formatNumber(Q.FrictionBrakeEnergy_kWh,3),'kWh','Residual braking beyond regeneration'; ...
            'Unmet traction energy',formatNumber(Q.UnmetTractionEnergy_kWh,6),'kWh','Undelivered route demand'};
        runtime.SignalGroups=[ ...
            signalGroup('Vehicle speed','Speed (km/h)',"Vehicle speed",speed), ...
            signalGroup('Vehicle acceleration','Acceleration (m/s^2)',"Acceleration",acceleration), ...
            signalGroup('Vehicle distance','Distance (km)',"Vehicle distance",S.Vehicle.Distance_m(:)/1000)];

    otherwise
        available=S.Regeneration.Available_kW(:);
        toAux=S.Regeneration.ToAuxiliary_kW(:);
        toBattery=S.Regeneration.ToActiveBattery_kW(:);
        dump=S.Regeneration.ResistorLoadBank_kW(:);
        runtime.KPIRows={ ...
            'Available regenerative energy',formatNumber(Q.RegeneratedEnergy_kWh,3),'kWh','Recovered at the motor DC side'; ...
            'To auxiliary loads',formatNumber(Q.RegenerationToAuxiliaryEnergy_kWh,3),'kWh','First priority'; ...
            'To active battery',formatNumber(Q.RegenerationToActiveBatteryEnergy_kWh,3),'kWh','Second priority'; ...
            'To resistor load bank',formatNumber(Q.ResistorLoadBankEnergy_kWh,3),'kWh','Third priority'; ...
            'Peak available regeneration',formatNumber(max(available),2),'kW','Maximum recovered DC power'};
        runtime.SignalGroups=[ ...
            signalGroup('Regenerative allocation','Power (kW)', ...
                ["Available","To auxiliary","To active battery","To resistor"], ...
                [available toAux toBattery dump]), ...
            signalGroup('Cumulative regenerative energy','Energy (kWh)', ...
                ["Available","Auxiliary","Active battery","Resistor"], ...
                [cumsum(available.*dt) cumsum(toAux.*dt) cumsum(toBattery.*dt) cumsum(dump.*dt)]/3600)];
end
runtime.SignalOptions=buildSignalOptions(runtime.SignalGroups,dt);
end

function runtime=externalChargerRuntime(runtime,result)
Q=result.Summary;
runtime.KPIRows={ ...
    'Grid-equivalent replenishment',formatNumber(Q.GridEquivalentEnergy_kWh,3),'kWh','Terminal energy replacement at configured grid efficiency'; ...
    'Electricity cost',formatNumber(Q.ElectricCost,2),'EUR','Grid-equivalent energy times configured tariff'; ...
    'External charger power', 'NOT AVAILABLE','kW','Charger rating and time-resolved charging are not simulated'; ...
    'Charging duration','NOT AVAILABLE','h','Requires charger rating, taper, thermal and infrastructure models'};
runtime.SignalGroups=[ ...
    unavailableSignalGroup('External charger power','No time-resolved depot/grid charger signal is simulated.'), ...
    unavailableSignalGroup('Charging session','The mission result contains replenishment energy, not a physical charging session.')];
runtime.SignalNote="The current model reports grid-equivalent replenishment after the mission. It does not simulate charger voltage, current, power, taper, temperature, or charging duration.";
end

function mechanical=motorMechanicalPower(result)
wheel=result.Signals.Wheel.Delivered_kW(:); drive=result.InputParameters.FinalDrive;
mechanical=zeros(size(wheel)); motoring=wheel>=0;
mechanical(motoring)=wheel(motoring)/max(drive.MotoringEfficiency,eps);
mechanical(~motoring)=wheel(~motoring)*drive.RegenEfficiency;
end

function groups=emptySignalGroups
groups=[ ...
    unavailableSignalGroup('Signal plot 1','Run a simulation to view component signals.'), ...
    unavailableSignalGroup('Signal plot 2','Run a simulation to view component signals.')];
end

function options=buildSignalOptions(groups,dt)
% Add energy-domain views without changing the two legacy default groups.
options=groups;
titles=lower(string({groups.Title}));
alreadyHasCumulative=any(contains(titles,"cumulative"));
for index=1:numel(groups)
    group=groups(index);
    isPower=group.Available && contains(lower(group.YLabel),"power") && ...
        size(group.Values,1)==numel(dt);
    if ~isPower || alreadyHasCumulative
        continue
    end
    signedEnergy=cumsum(group.Values.*dt,1)/3600;
    throughputEnergy=cumsum(abs(group.Values).*dt,1)/3600;
    options(end+1)=signalGroup(group.Title+" — cumulative signed energy", ...
        'Energy (kWh)',group.Names+" net energy",signedEnergy); %#ok<AGROW>
    options(end+1)=signalGroup(group.Title+" — cumulative throughput", ...
        'Energy throughput (kWh)',group.Names+" throughput",throughputEnergy); %#ok<AGROW>
end
end

function group=signalGroup(titleText,yLabel,names,values)
names=string(names); values=double(values);
if isvector(values), values=values(:); end
group=struct('Title',string(titleText),'YLabel',string(yLabel), ...
    'Names',names(:).','Values',values,'Available',true,'Message',"");
end

function group=unavailableSignalGroup(titleText,message)
group=struct('Title',string(titleText),'YLabel',"",'Names',strings(1,0), ...
    'Values',zeros(0,0),'Available',false,'Message',string(message));
end

function dt=timeStep(t)
if numel(t)>1
    dt=[diff(t);median(diff(t))];
else
    dt=ones(size(t));
end
end

function value=meanPositive(data)
positive=data(data>0);
if isempty(positive), value=0; else, value=mean(positive); end
end

function textValue=formatNumber(value,precision)
if ~isfinite(value)
    textValue='NOT AVAILABLE';
elseif precision==0
    textValue=sprintf('%.0f',value);
else
    textValue=sprintf(['%.' num2str(precision) 'f'],value);
end
end

function textValue=scopeText(result)
mode=string(result.Summary.PowertrainMode);
if isfield(result.InputParameters,'RepeatUntilDepleted') && result.InputParameters.RepeatUntilDepleted
    textValue=mode+" displayed result | repeat route until depleted";
else
    textValue=mode+" displayed result | selected mission";
end
end
