function create_default_database(databaseFile)
%CREATE_DEFAULT_DATABASE Create the synthetic HybridBus Excel master database.
arguments
    databaseFile (1,1) string = fullfile(hybrid_bus_project_root(), ...
        "data","HybridBus_ComponentDatabase.xlsx")
end
if isfile(databaseFile)
    delete(databaseFile);
end

n = 12;
ids = compose("%02d", (1:n)');
enabled = true(n,1);
synthetic = repmat("Synthetic engineering concept data", n, 1);
maker = repmat("Concept Manufacturer", n, 1);

Battery = table("BAT-"+ids, "Battery Pack "+ids, maker, ...
    linspace(110,220,n)', linspace(100,200,n)', linspace(600,800,n)', ...
    linspace(500,680,n)', linspace(720,920,n)', linspace(300,500,n)', ...
    linspace(150,280,n)', 0.94+0.003*(0:n-1)', 0.92+0.004*(0:n-1)', ...
    0.10*ones(n,1), 0.95*ones(n,1), linspace(120,240,n)', ...
    linspace(850,1450,n)', linspace(0.90,1.00,n)', repmat("LFP",n,1), ...
    round(linspace(600,800,n)'/50)*50, enabled, synthetic, ...
    'VariableNames', {'ComponentID','Name','Manufacturer','NominalEnergy_kWh', ...
    'UsableEnergy_kWh','NominalVoltage_V','MinVoltage_V','MaxVoltage_V', ...
    'MaxDischarge_kW','MaxCharge_kW','DischargeEfficiency','ChargeEfficiency', ...
    'MinSOE','MaxSOE','MaxRegen_kW','Mass_kg','DeratingFactor','Chemistry', ...
    'VoltageClass_V','OptimizationEnabled','Notes'});

Motor = table("MOT-"+ids, "Rear Hub Motor "+ids, maker, ...
    linspace(180,320,n)', linspace(110,220,n)', linspace(2200,4000,n)', ...
    linspace(1100,2400,n)', linspace(3500,6000,n)', linspace(900,1700,n)', ...
    linspace(0.90,0.96,n)', linspace(0.78,0.91,n)', linspace(90,190,n)', ...
    round(linspace(600,800,n)'/50)*50, repmat("Rear wheel hub",n,1), ...
    linspace(6,14,n)', linspace(10,22,n)', enabled, synthetic, ...
    'VariableNames', {'ComponentID','Name','Manufacturer','PeakPower_kW', ...
    'ContinuousPower_kW','PeakTorque_Nm','ContinuousTorque_Nm','MaxSpeed_rpm', ...
    'BaseSpeed_rpm','MotoringEfficiency','RegenEfficiency','Mass_kg', ...
    'VoltageClass_V','WheelSideCompatibility','MinReductionRatio', ...
    'MaxReductionRatio','OptimizationEnabled','Notes'});

Genset = table("GEN-"+ids, "Engine Genset "+ids, maker, ...
    linspace(120,260,n)', linspace(110,250,n)', linspace(25,45,n)', ...
    linspace(85,190,n)', linspace(110,250,n)', linspace(1.5,2.6,n)', ...
    linspace(0.04,0.08,n)', 0.835*ones(n,1), linspace(20,45,n)', ...
    linspace(60,100,n)', linspace(45,75,n)', linspace(35,65,n)', ...
    enabled, linspace(700,1150,n)', repmat("Diesel",n,1), synthetic, ...
    'VariableNames', {'ComponentID','Name','Manufacturer','EngineRatedPower_kW', ...
    'GeneratorRatedPower_kW','MinStablePower_kW','OptimumPower_kW','MaxPower_kW', ...
    'IdleFuel_Lph','StartFuel_L','FuelDensity_kg_L','WarmupTime_s','MinOnTime_s', ...
    'MinOffTime_s','RampRate_kW_s','StartStopEnable','Mass_kg','FuelType','Notes'});

Engine = table("ENG-"+ids, "Diesel Engine "+ids, maker, linspace(120,260,n)', ...
    linspace(190,225,n)', linspace(205,245,n)', linspace(240,285,n)', ...
    enabled, synthetic, 'VariableNames', {'ComponentID','Name','Manufacturer', ...
    'RatedPower_kW','BestBSFC_g_kWh','LowLoadBSFC_g_kWh','HighLoadBSFC_g_kWh', ...
    'OptimizationEnabled','Notes'});

Generator = table("GNR-"+ids, "Generator "+ids, maker, linspace(110,250,n)', ...
    linspace(0.91,0.96,n)', linspace(0.87,0.93,n)', round(linspace(600,800,n)'/50)*50, ...
    enabled, synthetic, 'VariableNames', {'ComponentID','Name','Manufacturer', ...
    'RatedPower_kW','PeakEfficiency','LowLoadEfficiency','VoltageClass_V', ...
    'OptimizationEnabled','Notes'});

Tyre = table("TYR-"+ids, "Bus Tyre "+ids, maker, linspace(0.47,0.54,n)', ...
    linspace(0.0055,0.0090,n)', linspace(3200,4300,n)', enabled, synthetic, ...
    'VariableNames', {'ComponentID','Name','Manufacturer','LoadedRadius_m', ...
    'RollingResistanceCoefficient','MaxLoad_kg','OptimizationEnabled','Notes'});

Drive = table("FD-"+ids, "Fixed Reduction "+ids, maker, linspace(8,18,n)', ...
    linspace(0.955,0.985,n)', linspace(0.92,0.97,n)', linspace(55,100,n)', ...
    enabled, synthetic, 'VariableNames', {'ComponentID','Name','Manufacturer', ...
    'Ratio','MotoringEfficiency','RegenEfficiency','Mass_kg', ...
    'OptimizationEnabled','Notes'});

totalMass = round(linspace(19000,60000,n)'/100)*100;
massNames = "Total Vehicle Mass "+string(totalMass)+" kg";
massNotes = repmat("TotalVehicleMass_kg includes curb, occupants, cargo, and powertrain",n,1);
Mass = table("MASS-"+ids, massNames, totalMass, linspace(11500,14500,n)', ...
    round(linspace(0,65,n))', 75*ones(n,1), linspace(200,700,n)', enabled, massNotes, ...
    'VariableNames', {'ComponentID','Name','TotalVehicleMass_kg','CurbMass_kg', ...
    'PassengerCount','PassengerMass_kg','CargoMass_kg','OptimizationEnabled','Notes'});

Aux = table("AUX-"+ids, "Auxiliary Profile "+ids, linspace(4,22,n)', ...
    linspace(0.20,0.65,n)', linspace(0.25,0.85,n)', linspace(18,24,n)', ...
    enabled, synthetic, 'VariableNames', {'ComponentID','Name','BasePower_kW', ...
    'ColdHVAC_kW_per_C','HotHVAC_kW_per_C','ComfortTemperature_C', ...
    'OptimizationEnabled','Notes'});

Environment = table("ENV-"+ids, "Ambient "+ids, linspace(-10,45,n)', ...
    linspace(1.34,1.12,n)', linspace(0,12,n)', enabled, synthetic, ...
    'VariableNames', {'ComponentID','Name','Temperature_C','AirDensity_kg_m3', ...
    'Headwind_m_s','OptimizationEnabled','Notes'});

Control = table("CAL-"+ids, "Control Calibration "+ids, ...
    0.30*ones(n,1), linspace(0.34,0.50,n)', linspace(0.55,0.70,n)', ...
    linspace(0.68,0.82,n)', linspace(60,180,n)', linspace(40,100,n)', ...
    0.95*ones(n,1), enabled, synthetic, ...
    'VariableNames', {'ComponentID','Name','SwitchLowSOE','GensetStartSOE', ...
    'GensetStopSOE','RegenRedirectSOE','MinActiveTime_s','MinGensetTime_s', ...
    'GensetTargetSOE','OptimizationEnabled','Notes'});
Control.Notes(:)="Fixed 30% role-swap threshold; optimum-power genset charges standby to its upper SOE limit";

Vehicle = table(9.81, 0.62, 7.8, 0.0065, 420, 0.96, 0.3, 0.001, 1.0, ...
    'VariableNames', {'Gravity_m_s2','DragCoefficient','FrontalArea_m2', ...
    'RollingResistanceCoefficient','FuelTank_L','GridChargeEfficiency', ...
    'AccelerationFilterTau_s','EnergyBalanceTolerance_kWh','SampleTime_s'});

prices = table(2.10, 0.40, false, 'VariableNames', ...
    {'FuelPrice_per_L','ElectricityPrice_per_kWh','CreditTerminalSurplus'});
opt = table(100, true, 0.03, "EquivalentReplenishment", ...
    'VariableNames', {'MaxConfigurations','CompatibilityFilter','TerminalSOETolerance', ...
    'ComparisonMethod'});

% Three official VECTO missions, eight OSM/OSRM European long-distance
% corridors, and nine geographic German city cycles.
routeFolder=fullfile(hybrid_bus_project_root(),'documentation','reference_routes');
vectoFiles=["VECTO_Urban.vdri","VECTO_Suburban.vdri","VECTO_Coach.vdri"];
vectoIDs=["VECTO-URBAN","VECTO-SUBURBAN","VECTO-COACH"];
vectoNames=["EU VECTO Urban Bus","EU VECTO Suburban Bus","EU VECTO Coach"];
vectoTypes=["Urban","Semi-urban / Suburban","Coach"];
RouteTime=table; RouteDistance=table; RouteGeometry=table;
longRouteFolder=fullfile(routeFolder,'osrm');
longRouteFiles=["OSRM_Berlin_Vienna.json","OSRM_Hamburg_Paris.json", ...
    "OSRM_Munich_Rome.json","OSRM_Amsterdam_Zurich.json", ...
    "OSRM_Stockholm_Copenhagen.json","OSRM_Prague_Brussels.json", ...
    "OSRM_Warsaw_Prague.json","OSRM_Frankfurt_Milan.json"];
longRouteIDs=["EUR-BER-VIE","EUR-HAM-PAR","EUR-MUC-ROM","EUR-AMS-ZRH", ...
    "EUR-STO-CPH","EUR-PRG-BRU","EUR-WAW-PRG","EUR-FRA-MIL"];
longRouteNames=["Berlin, Germany to Vienna, Austria"; ...
    "Hamburg, Germany to Paris, France"; ...
    "Munich, Germany to Rome, Italy"; ...
    "Amsterdam, Netherlands to Zurich, Switzerland"; ...
    "Stockholm, Sweden to Copenhagen, Denmark"; ...
    "Prague, Czechia to Brussels, Belgium"; ...
    "Warsaw, Poland to Prague, Czechia"; ...
    "Frankfurt, Germany to Milan, Italy"];
longRouteRegions=["Germany / Austria";"Germany / France"; ...
    "Germany / Austria / Italy";"Netherlands / Germany / Switzerland"; ...
    "Sweden / Denmark";"Czechia / Germany / Belgium"; ...
    "Poland / Czechia";"Germany / Switzerland / Italy"];
longRouteCount=numel(longRouteIDs);
cityRouteFolder=fullfile(routeFolder,'osrm_city');
cityRouteFiles=["OSRM_Mannheim_City.json","OSRM_Stuttgart_City.json", ...
    "OSRM_Berlin_City.json","OSRM_Munich_City.json","OSRM_Hamburg_City.json", ...
    "OSRM_Frankfurt_City.json","OSRM_Cologne_City.json", ...
    "OSRM_Dusseldorf_City.json","OSRM_Leipzig_City.json"];
cityRouteIDs=["DE-MAN-CITY","DE-STR-CITY","DE-BER-CITY","DE-MUC-CITY", ...
    "DE-HAM-CITY","DE-FRA-CITY","DE-CGN-CITY","DE-DUS-CITY","DE-LEJ-CITY"];
cityRouteNames=["Mannheim Urban Circuit";"Stuttgart Urban Circuit"; ...
    "Berlin Urban Circuit";"Munich Urban Circuit";"Hamburg Urban Circuit"; ...
    "Frankfurt Urban Circuit";"Cologne Urban Circuit"; ...
    "Dusseldorf Urban Circuit";"Leipzig Urban Circuit"];
cityRouteCount=numel(cityRouteIDs);
routeRows=cell(n+longRouteCount,19);
for routeIndex=1:3
    [rt,rd,meta]=convert_vecto_distance_cycle(fullfile(routeFolder,vectoFiles(routeIndex)), ...
        vectoIDs(routeIndex),vectoNames(routeIndex),vectoTypes(routeIndex));
    if routeIndex==1, RouteTime=rt; RouteDistance=rd;
    else, RouteTime=[RouteTime;rt]; RouteDistance=[RouteDistance;rd]; end %#ok<AGROW>
    routeRows(routeIndex,:)={vectoIDs(routeIndex),vectoNames(routeIndex),vectoTypes(routeIndex), ...
        "European Union (applicable in Germany)","Official distance-based regulatory mission profile", ...
        "European Commission Joint Research Centre","https://code.europa.eu/vecto/vecto", ...
        "d16ba783c1d8af0ea68797f5d7ed6cf01877d402","EUPL-1.2",meta.Distance_km, ...
        meta.Duration_s,meta.MaximumSpeed_kmh,true, ...
        "Raw VECTO trace retained; time trace is a deterministic 1 Hz conversion", ...
        false,NaN,NaN,NaN,NaN};
end
for longIndex=1:longRouteCount
    catalogIndex=3+longIndex;
    [rt,rd,meta]=convert_osrm_coach_route( ...
        fullfile(longRouteFolder,longRouteFiles(longIndex)), ...
        longRouteIDs(longIndex),longRouteNames(longIndex),"Long-distance coach");
    [geometry,geoMeta]=geometry_table_from_osrm( ...
        fullfile(longRouteFolder,longRouteFiles(longIndex)), ...
        longRouteIDs(longIndex),longRouteNames(longIndex));
    if longIndex==1, RouteGeometry=geometry;
    else, RouteGeometry=[RouteGeometry;geometry]; end %#ok<AGROW>
    RouteTime=[RouteTime;rt]; RouteDistance=[RouteDistance;rd]; %#ok<AGROW>
    routeRows(catalogIndex,:)={longRouteIDs(longIndex),longRouteNames(longIndex), ...
        "Long-distance coach",longRouteRegions(longIndex), ...
        "OSM road corridor routed by OSRM; coach speed/rest adaptation", ...
        "© OpenStreetMap contributors; Project OSRM", ...
        "https://www.openstreetmap.org/copyright",meta.RetrievedUTC,"ODbL 1.0", ...
        meta.Distance_km,meta.Duration_s,meta.MaximumSpeed_kmh,true, ...
        "100 km/h cap; 45 min rest after 4.5 h driving; simulation grade unavailable and set to zero; display elevation from Copernicus DEM GLO-90", ...
        true,geoMeta.OriginLatitude_deg,geoMeta.OriginLongitude_deg, ...
        geoMeta.DestinationLatitude_deg,geoMeta.DestinationLongitude_deg};
end
for cityIndex=1:cityRouteCount
    [rt,rd,meta]=convert_osrm_city_route( ...
        fullfile(cityRouteFolder,cityRouteFiles(cityIndex)), ...
        cityRouteIDs(cityIndex),cityRouteNames(cityIndex));
    [geometry,geoMeta]=geometry_table_from_osrm( ...
        fullfile(cityRouteFolder,cityRouteFiles(cityIndex)), ...
        cityRouteIDs(cityIndex),cityRouteNames(cityIndex));
    RouteTime=[RouteTime;rt]; RouteDistance=[RouteDistance;rd]; %#ok<AGROW>
    RouteGeometry=[RouteGeometry;geometry]; %#ok<AGROW>
    catalogIndex=3+longRouteCount+cityIndex;
    routeRows(catalogIndex,:)={cityRouteIDs(cityIndex),cityRouteNames(cityIndex), ...
        "Geographic German city cycle","Germany / urban", ...
        "OSM urban road circuit routed by OSRM; deterministic bus-stop adaptation", ...
        "© OpenStreetMap contributors; Project OSRM", ...
        "https://www.openstreetmap.org/copyright",meta.RetrievedUTC,"ODbL 1.0", ...
        meta.Distance_km,meta.Duration_s,meta.MaximumSpeed_kmh,true, ...
        "50 km/h cap; 20 s dwell at nominal 800 m stops; simulation grade unavailable and set to zero; display elevation from Copernicus DEM GLO-90", ...
        true,geoMeta.OriginLatitude_deg,geoMeta.OriginLongitude_deg, ...
        geoMeta.DestinationLatitude_deg,geoMeta.DestinationLongitude_deg};
end
RouteCatalog=cell2table(routeRows,'VariableNames',{'RouteID','RouteName','RouteType', ...
    'Region','DataBasis','SourceOrganization','SourceURL','SourceVersion','License', ...
    'Distance_km','Duration_s','MaximumSpeed_kmh','OptimizationEnabled','Notes', ...
    'HasGeolocation','OriginLatitude_deg','OriginLongitude_deg', ...
    'DestinationLatitude_deg','DestinationLongitude_deg'});
RouteGrade = RouteDistance(:,{'RouteID','RouteName','Distance_m','Grade_pct'});

fuelLoad = (0:0.1:1)';
FuelMap = table(fuelLoad, 330-260*fuelLoad+155*fuelLoad.^2, ...
    'VariableNames', {'NormalizedEngineLoad','BSFC_g_kWh'});
GeneratorMap = table(fuelLoad, 0.82+0.14*sin(pi*fuelLoad/2), ...
    'VariableNames', {'NormalizedGeneratorLoad','Efficiency'});

definitions = {
    'P_bat_kW','Positive when battery supplies DC bus; negative when charging','kW';
    'P_wheel_kW','Positive traction; negative braking demand','kW';
    'SOE','Stored usable energy divided by nominal usable energy','1';
    'E_grid_equiv','Terminal battery deficit divided by grid charge efficiency','kWh';
    'Fuel_L','Diesel volume consumed from BSFC and start penalty','L';
    'Cost_per_km','Fuel plus grid-equivalent electricity cost divided by route distance','currency/km'};
Units = cell2table(definitions,'VariableNames',{'Term','Definition','Unit'});
ChangeLog = table([datetime('now');datetime('now');datetime('now');datetime('now');datetime('now');datetime('now');datetime('now');datetime('now');datetime('now');datetime('now')], ...
    ["1.0.0";"1.1.0";"1.2.0";"1.3.0";"1.4.0";"1.5.0";"1.6.0";"1.6.1";"1.7.0";"1.7.1"], ...
    ["Initial synthetic concept database"; ...
    "Added official EU VECTO Urban, Suburban and Coach missions"; ...
    "Expanded explicit total vehicle mass variants from 19000 kg to 60000 kg"; ...
    "Added eight OSM/OSRM European long-distance coach corridors from 638 to 916 km"; ...
    "Separated genset from traction bus; fixed 30% battery role swap and constant optimum-power standby charging"; ...
    "Added OSRM latitude/longitude route geometry and endpoint metadata for geographic corridors"; ...
    "Replaced nine synthetic concept routes with geographic German city circuits"; ...
    "Changed the default initial Battery 2 SOE from 75% to 20%"; ...
    "Added cached Copernicus DEM GLO-90 elevation to geographic route geometry for 3D mapping"; ...
    "Added Hybrid whole-set and BEV half-set battery bank multiplication"], ...
    ["Codex";"Codex";"Codex";"Codex";"Codex";"Codex";"Codex";"Codex";"Codex";"Codex"], ...
    'VariableNames',{'Timestamp','Version','Change','Author'});

dashboard = {
    'Hybrid-Electric Bus Component Database','Value','Unit / note';
    'DatabaseVersion','1.7.1','Battery set multiplier; Initial B2 SOE 20%; geographic routes include 3D elevation';
    'SelectedRoute','VECTO-URBAN','ID';
    'SelectedBattery1','BAT-12','ID';
    'SelectedBattery2','BAT-12','ID';
    'SelectedMotor','MOT-12','ID';
    'SelectedGenset','GEN-05','ID';
    'SelectedTyre','TYR-05','ID';
    'SelectedFinalDrive','FD-08','ID';
    'SelectedMass','MASS-01','ID (19000 kg total vehicle mass)';
    'SelectedAuxProfile','AUX-04','ID';
    'SelectedEnvironment','ENV-07','ID';
    'SelectedControl','CAL-05','ID';
    'FuelPrice',2.10,'EUR/L';
    'ElectricityPrice',0.40,'EUR/kWh';
    'InitialBattery1SOE',0.85,'fraction (app displays %)';
    'InitialBattery2SOE',0.20,'fraction (app displays %)';
    'InitialActiveBattery',1,'1 or 2';
    'BatterySetMultiplier',1,'Hybrid: whole sets; BEV: 0.5-set increments';
    'OperatingMode','Manual Configuration','Manual Configuration / Automatic Optimization';
    'OptimizationMode','EquivalentReplenishment','EquivalentReplenishment / ChargeSustaining';
    'FuelTankCapacity',420,'L';
    'AuxiliaryScalarOverride',1.0,'multiplier';
    'InputWarnings','Run validate_hybrid_bus_database.m','status';
    'ConfigurationSummary','Two rear hub motors; dual batteries; diesel genset','text'};
writecell(dashboard,databaseFile,'Sheet','Dashboard','Range','A1');

sheetTables = {
    'Battery_Catalog',Battery; 'Motor_Catalog',Motor; 'Genset_Catalog',Genset;
    'Engine_Catalog',Engine; 'Generator_Catalog',Generator;
    'Engine_Fuel_Map',FuelMap; 'Generator_Efficiency_Map',GeneratorMap;
    'Tyre_Catalog',Tyre; 'Final_Drive_Catalog',Drive; 'Bus_Mass_Catalog',Mass;
    'Vehicle_Parameters',Vehicle; 'Aux_Load_Profiles',Aux; 'Route_Catalog',RouteCatalog;
    'Route_Geometry',RouteGeometry;
    'Route_Time_Speed',RouteTime; 'Route_Distance_Speed',RouteDistance;
    'Route_Grade',RouteGrade; 'Environment',Environment;
    'Control_Calibration',Control; 'Energy_Prices',prices;
    'Optimization_Settings',opt; 'Units_and_Definitions',Units; 'Change_Log',ChangeLog};
for index = 1:size(sheetTables,1)
    writetable(sheetTables{index,2},databaseFile,'Sheet',sheetTables{index,1}, ...
        'WriteMode','overwritesheet');
end
format_workbook(databaseFile, sheetTables);
fprintf('Created %s with %d sheets.\n',databaseFile,size(sheetTables,1)+1);
end

function [Geometry,Metadata]=geometry_table_from_osrm(sourceFile,routeID,routeName)
payload=jsondecode(fileread(sourceFile));
route=payload.OSRMResponse.routes(1);
assert(isfield(route,'geometry') && isfield(route.geometry,'coordinates'), ...
    'HybridBus:RouteGeometry','GeoJSON geometry is missing for %s.',routeID);
coordinates=double(route.geometry.coordinates);
assert(size(coordinates,2)==2 && size(coordinates,1)>=2, ...
    'HybridBus:RouteGeometry','Invalid longitude/latitude geometry for %s.',routeID);
sampleCount=min(1200,size(coordinates,1));
sampleIndex=unique(round(linspace(1,size(coordinates,1),sampleCount)))';
coordinates=coordinates(sampleIndex,:);
longitude=coordinates(:,1); latitude=coordinates(:,2);
earthRadiusKm=6371.0088;
lat1=deg2rad(latitude(1:end-1)); lat2=deg2rad(latitude(2:end));
dLat=lat2-lat1; dLon=deg2rad(diff(longitude));
a=sin(dLat/2).^2+cos(lat1).*cos(lat2).*sin(dLon/2).^2;
segmentKm=2*earthRadiusKm*atan2(sqrt(a),sqrt(max(0,1-a)));
cumulativeDistanceKm=[0;cumsum(segmentKm)];
nGeometry=numel(latitude);
elevationCacheFile=fullfile(hybrid_bus_project_root(), ...
    'documentation','reference_routes','elevation','Route_Elevation_GLO90.csv');
assert(isfile(elevationCacheFile),'HybridBus:ElevationCacheMissing', ...
    'Elevation cache is missing: %s',elevationCacheFile);
persistent elevationCache
if isempty(elevationCache)
    elevationCache=readtable(elevationCacheFile,'TextType','string');
end
routeElevation=sortrows(elevationCache(elevationCache.RouteID==routeID,:),'Sequence');
assert(height(routeElevation)==nGeometry && ...
    isequal(routeElevation.Sequence,(1:nGeometry)'), ...
    'HybridBus:ElevationCacheMismatch', ...
    'Elevation cache does not match route geometry for %s.',routeID);
elevationSource="Copernicus DEM 2021 GLO-90 via Open-Meteo; " + ...
    "100 sourced route points with linear distance interpolation";
Geometry=table(repmat(routeID,nGeometry,1),repmat(routeName,nGeometry,1), ...
    (1:nGeometry)',latitude,longitude,cumulativeDistanceKm,routeElevation.Elevation_m, ...
    repmat("OSRM GeoJSON / OpenStreetMap",nGeometry,1), ...
    repmat(string(payload.RetrievedUTC),nGeometry,1), ...
    repmat(elevationSource,nGeometry,1),routeElevation.RetrievedUTC, ...
    'VariableNames',{'RouteID','RouteName','Sequence','Latitude_deg', ...
    'Longitude_deg','CumulativeDistance_km','Elevation_m','GeometrySource','RetrievedUTC', ...
    'ElevationSource','ElevationRetrievedUTC'});
Metadata=struct('OriginLatitude_deg',latitude(1), ...
    'OriginLongitude_deg',longitude(1), ...
    'DestinationLatitude_deg',latitude(end), ...
    'DestinationLongitude_deg',longitude(end));
end

function format_workbook(databaseFile, ~)
% Formatting and validation are best-effort; data generation is independent.
try
    excel = actxserver('Excel.Application');
    cleanup = onCleanup(@() quit_excel(excel));
    excel.DisplayAlerts = false;
    workbook = excel.Workbooks.Open(char(databaseFile));
    inputColor = 13561798; % pale yellow (BGR)
    headerColor = 12611584; % blue (BGR)
    for index = 1:workbook.Worksheets.Count
        sheet = workbook.Worksheets.Item(index);
        used = sheet.UsedRange;
        used.Font.Name = 'Aptos';
        used.Columns.AutoFit;
        used.Rows.Item(1).Font.Bold = true;
        used.Rows.Item(1).Interior.Color = headerColor;
        used.Rows.Item(1).Font.Color = 16777215;
        sheet.Application.ActiveWindow.SplitRow = 1;
        sheet.Application.ActiveWindow.FreezePanes = true;
        if index > 1 && used.Rows.Count > 1 && used.Columns.Count > 0
            try
                sheet.ListObjects.Add(1,used,[],1).Name = sprintf('tbl_%02d',index);
            catch
            end
        end
    end
    dash = workbook.Worksheets.Item('Dashboard');
    dash.Range('B2:B24').Interior.Color = inputColor;
    dash.Columns.Item('A').ColumnWidth = 31;
    dash.Columns.Item('B').ColumnWidth = 34;
    dash.Columns.Item('C').ColumnWidth = 34;

    names = {'RouteIDs','BatteryIDs','MotorIDs','GensetIDs','TyreIDs','DriveIDs', ...
        'MassIDs','AuxIDs','EnvironmentIDs','ControlIDs'};
    sheets = {'Route_Catalog','Battery_Catalog','Motor_Catalog','Genset_Catalog', ...
        'Tyre_Catalog','Final_Drive_Catalog','Bus_Mass_Catalog','Aux_Load_Profiles', ...
        'Environment','Control_Calibration'};
    cells = {'B3','B4','B6','B7','B8','B9','B10','B11','B12','B13'};
    for index = 1:numel(names)
        src = workbook.Worksheets.Item(sheets{index});
        lastCell = get(src.Cells,'Item',src.Rows.Count,1);
        lastRow = lastCell.End(-4162).Row;
        workbook.Names.Add(names{index},sprintf("='%s'!$A$2:$A$%d",sheets{index},lastRow));
        range = dash.Range(cells{index});
        range.Validation.Delete;
        range.Validation.Add(3,1,1,"="+names{index});
    end
    dash.Range('B5').Validation.Delete;
    dash.Range('B5').Validation.Add(3,1,1,'=BatteryIDs');
    dash.Range('B19').Validation.Add(3,1,1,'Manual Configuration,Automatic Optimization');
    dash.Range('B20').Validation.Add(3,1,1,'EquivalentReplenishment,ChargeSustaining');
    workbook.Save;
    workbook.Close(false);
    clear cleanup
    quit_excel(excel);
catch exception
    warning('HybridBus:ExcelFormatting', ...
        'Workbook created; advanced Excel formatting was limited: %s',exception.message);
end
end

function quit_excel(excel)
try
    excel.Quit;
    delete(excel);
catch
end
end
