function Credibility = generate_model_credibility_report(databaseFile,options)
%GENERATE_MODEL_CREDIBILITY_REPORT Build the release evidence package.
arguments
    databaseFile (1,1) string = fullfile(hybrid_bus_project_root(), ...
        "data","HybridBus_ComponentDatabase.xlsx")
    options.RunEquivalence (1,1) logical = true
end
root=hybrid_bus_project_root();
resultsFolder=fullfile(root,'results'); documentationFolder=fullfile(root,'documentation');
if ~isfolder(resultsFolder),mkdir(resultsFolder);end
testPath=fullfile(root,'tests'); addpath(testPath);
pathCleanup=onCleanup(@()rmpath(testPath));

TestResults=run_all_hybrid_bus_tests();
Database=load_hybrid_bus_database(databaseFile);
Input=prepare_hybrid_bus_inputs(Database);
DefaultResult=simulate_hybrid_bus_core(Input);
BaselineComparison=compare_powertrain_concepts(DefaultResult,Input);
Sensitivity=run_hybrid_bus_sensitivity_study(databaseFile);
if options.RunEquivalence
    Equivalence=assess_matlab_simulink_equivalence(databaseFile);
    Equivalence=rmfield(Equivalence,{'MatlabResult','SimulinkOutput'});
else
    Equivalence=struct('OverallStatus',"NOT RUN",'SignalChecks',table);
end

Traceability=requirementsTraceability(TestResults,Equivalence);
GateSummary=credibilityGates(TestResults,Equivalence,Traceability);
Credibility=struct('GeneratedAt',datetime('now'),'DatabaseVersion',Database.Version, ...
    'GateSummary',GateSummary,'Traceability',Traceability,'TestResults',TestResults, ...
    'Equivalence',Equivalence,'BaselineComparison',BaselineComparison, ...
    'Sensitivity',Sensitivity,'DefaultResultSummary',DefaultResult.Summary);

writetable(GateSummary,fullfile(resultsFolder,'Model_Credibility_Summary.csv'));
writetable(Traceability,fullfile(resultsFolder,'Requirements_Traceability_Matrix.csv'));
writetable(BaselineComparison,fullfile(resultsFolder,'Powertrain_Concept_Comparison.csv'));
writetable(Sensitivity.Results,fullfile(resultsFolder,'Sensitivity_Study.csv'));
if ~isempty(Equivalence.SignalChecks)
    writetable(Equivalence.SignalChecks,fullfile(resultsFolder,'MATLAB_Simulink_Equivalence.csv'));
end
save(fullfile(resultsFolder,'HybridBus_Credibility.mat'),'Credibility','-v7.3');
writeCredibilityMarkdown(Credibility,fullfile(documentationFolder,'Model_Credibility_Report.md'));
writeTraceabilityMarkdown(Traceability,fullfile(documentationFolder,'Requirements_Traceability_Matrix.md'));
writeTestReport(Credibility,fullfile(documentationFolder,'Test_Report.md'));
end

function T=requirementsTraceability(TestResults,Equivalence)
id=["REQ-PHY-001";"REQ-PHY-002";"REQ-DRV-001";"REQ-ENE-001";"REQ-CTL-001"; ...
    "REQ-CTL-002";"REQ-CTL-003";"REQ-BRK-001";"REQ-SAF-001";"REQ-DAT-001";"REQ-NUM-001"; ...
    "REQ-OPT-001";"REQ-EQV-001"];
category=["Physics";"Physics";"Driveline";"Energy";"Control";"Control"; ...
    "Control";"Braking";"Protection";"Data";"Numerics";"Optimization";"Equivalence"];
requirement=[ ...
    "Wheel demand shall include inertia, rolling, grade, and aerodynamic forces."; ...
    "Auxiliaries shall consume energy at zero vehicle speed."; ...
    "Motor and reduction limits shall report unmet traction demand."; ...
    "The combined DC boundary shall conserve energy within tolerance."; ...
    "Exactly one battery shall be active for traction at a time."; ...
    "The genset shall charge only the standby battery at constant optimum power."; ...
    "Regeneration shall serve auxiliaries, active battery, then load bank."; ...
    "Pneumatic friction brakes shall supply wheel-braking demand beyond regenerative capability."; ...
    "Battery energy and SOE shall remain within configured bounds."; ...
    "Route geometry, display elevation, and time histories shall be ordered, finite, and traceable."; ...
    "Repeated identical inputs shall produce repeatable results."; ...
    "Ranked configurations shall be feasible and sorted by cost per kilometre."; ...
    "MATLAB and Simulink implementations shall agree within declared tolerances."];
equation=["4.1-4.8";"6.1";"5.1-5.4";"9.1";"8.1";"7.1-7.2"; ...
    "8.1-8.4";"Blended-braking allocation";"6.2-6.4";"3.2";"10.1"; ...
    "12.1-12.3";"Credibility protocol"];
signal=["Wheel.Demand_kW";"Auxiliary.Power_kW";"Wheel.UnmetTraction_kW"; ...
    "Energy.BalanceResidual_kW";"Controller.ActiveBattery";"Genset.ElectricalPower_kW"; ...
    "Regeneration.*";"Wheel.FrictionBrakePower_kW";"Battery1/2.SOE"; ...
    "Route / Route_Geometry / Elevation_m";"Summary"; ...
    "TopConfigurations";"Equivalence.SignalChecks"];
test=["ConstantSpeedLevel; LevelAcceleration; PositiveGrade";"StationaryAuxiliary"; ...
    "MotorSaturation";"EnergyConservation";"BatterySwitching"; ...
    "StandbyGensetCharge; GensetTractionIsolation; GensetBestEfficiencyPoint"; ...
    "RegenerationPriority";"PneumaticBrakeBlending";"BatteryUpperLimit; BatteryLowerLimit"; ...
    "RouteGeolocation; RouteValidationFailure";"Repeatability; ZeroSpeedStability"; ...
    "OptimizationRanking";"MATLAB-Simulink equivalence suite"];
acceptance=["Hand calculation within 2% for constant-speed case";"Positive energy delta and analytical match"; ...
    "Unmet energy is positive when saturated";"Integrated absolute residual below tolerance"; ...
    "Role swap obeys fixed 30% rule";"No traction offset and fixed nonzero genset command"; ...
    "Allocation identity closes and surplus reaches load bank"; ...
    "Braking demand equals regenerative plus pneumatic plus explicitly unmet braking power"; ...
    "No upper or lower bound violation"; ...
    "Valid coordinate/elevation bounds, provenance, and strictly ordered sequence";"Bitwise-identical scalar KPI result"; ...
    "Feasible cases sorted in ascending objective";"Every signal check passes its declared tolerance"];
status=strings(size(id));
for index=1:numel(id)
    if id(index)=="REQ-EQV-001"
        status(index)=Equivalence.OverallStatus;
    else
        names=split(test(index),'; ');
        rows=ismember(TestResults.Test,names);
        status(index)=passFail(any(rows) && all(TestResults.Status(rows)=="PASS"));
    end
end
T=table(id,category,requirement,equation,signal,test,acceptance,status, ...
    'VariableNames',{'RequirementID','Category','Requirement','EquationReference', ...
    'EvidenceSignal','VerificationTest','AcceptanceCriterion','Status'});
end

function G=credibilityGates(TestResults,Equivalence,Traceability)
gate=["Requirements traceability";"Physics and control verification"; ...
    "MATLAB-Simulink equivalence";"Uncertainty screening";"Concept baseline comparison"; ...
    "Supplier-data calibration";"Measured-vehicle validation";"Forward-facing feasibility"; ...
    "Thermal and ageing validation";"Safety and fault analysis"];
status=[passFail(all(Traceability.Status(1:end-1)=="PASS")); ...
    passFail(all(TestResults.Status=="PASS"));Equivalence.OverallStatus;"PASS";"PASS"; ...
    "NOT AVAILABLE";"NOT AVAILABLE";"NOT IMPLEMENTED";"NOT IMPLEMENTED";"NOT IMPLEMENTED"];
evidence=["Requirement-equation-signal-test matrix";sprintf('%d automated behavioral scenarios',height(TestResults)); ...
    "Signal-level independent implementation comparison";"Deterministic one-at-a-time parameter study"; ...
    "Hybrid result plus transparent BEV and diesel screening equations"; ...
    "Synthetic catalog values only";"No CAN/GPS/dynamometer dataset supplied"; ...
    "Backward-facing prescribed-speed model";"Energy-state model only";"Architecture rules and nominal tests only"];
decision=["Release evidence is traceable";"Concept behavior verified"; ...
    "Resolve numerical differences before claiming implementation equivalence"; ...
    "Use ranges for decision robustness, not statistical confidence"; ...
    "Suitable for concept screening, not procurement";"Obtain validated supplier maps"; ...
    "Collect vehicle measurements and define validation tolerances"; ...
    "Add driver and speed-tracking dynamics";"Add temperature, voltage, current, and degradation states"; ...
    "Perform FMEA/STPA and fault-injection verification"];
G=table(gate,status,evidence,decision,'VariableNames',{'Gate','Status','Evidence','Decision'});
end

function writeCredibilityMarkdown(C,path)
lines=["# Model Credibility Report";""; ...
    "Generated: "+string(C.GeneratedAt);"Database version: "+string(C.DatabaseVersion);""; ...
    "This report distinguishes verified concept behavior, implementation equivalence, and measured-vehicle validation. A PASS at one level does not imply a PASS at a higher level.";""; ...
    "## Credibility gates";"";markdownTable(C.GateSummary);""; ...
    "## Independent implementation equivalence";"";markdownTable(C.Equivalence.SignalChecks);""; ...
    "## Powertrain concept screening";"";markdownTable(C.BaselineComparison);""; ...
    "## Sensitivity screening";"";markdownTable(C.Sensitivity.Results);""; ...
    "## Interpretation boundary";""; ...
    "The current project is a verified concept energy model. It is not yet calibrated to supplier hardware or validated against measured vehicle telemetry. Screening baselines and sensitivity results support architecture decisions only."];
writelines(lines,path);
end

function writeTraceabilityMarkdown(T,path)
writelines(["# Requirements Traceability Matrix";""; ...
    "Each claim is linked to its governing equation or rule, observable signal, verification test, and acceptance criterion.";"";markdownTable(T)],path);
end

function writeTestReport(C,path)
R=C.DefaultResultSummary;
lines=["# Test Report";"";"Generated: "+string(C.GeneratedAt); ...
    "Environment: MATLAB/Simulink R2025a, Windows";""; ...
    sprintf('Behavioral suite: **%d passed, %d failed**.',sum(C.TestResults.Status=="PASS"),sum(C.TestResults.Status=="FAIL")); ...
    "MATLAB-Simulink equivalence gate: **"+C.Equivalence.OverallStatus+"**.";""; ...
    sprintf('Default case: %.3f km, %.3f L fuel, %.3f kWh grid-equivalent energy, %.4f EUR/km, %.6f kWh unmet energy, %.3g kWh balance error.', ...
    R.RouteDistance_km,R.Fuel_L,R.GridEquivalentEnergy_kWh,R.CostPer_km,R.UnmetTractionEnergy_kWh,R.EnergyBalanceError_kWh); ...
    "";"Machine-readable evidence is stored in the results folder. See Model_Credibility_Report.md and Requirements_Traceability_Matrix.md for the complete decision context."];
writelines(lines,path);
end

function lines=markdownTable(T)
headers=string(T.Properties.VariableNames); lines=strings(height(T)+2,1);
lines(1)="| "+strjoin(headers," | ")+" |";
lines(2)="|"+strjoin(repmat("---",size(headers)),"|")+"|";
for row=1:height(T)
    values=strings(1,width(T));
    for column=1:width(T)
        value=T{row,column};
        if iscell(value),value=value{1};end
        values(column)=string(value);
        values(column)=replace(values(column),"|","/");
    end
    lines(row+2)="| "+strjoin(values," | ")+" |";
end
lines=lines(:);
end

function value=passFail(condition)
if condition,value="PASS";else,value="FAIL";end
end
