function Credibility = generate_model_credibility_report(databaseFile,options)
%GENERATE_MODEL_CREDIBILITY_REPORT Build the release evidence package.
arguments
    databaseFile (1,1) string = fullfile(hybrid_bus_project_root(), ...
        "data","HybridBus_ComponentDatabase.xlsx")
    options.RunEquivalence (1,1) logical = true
end
root=hybrid_bus_project_root();
resultsFolder=fullfile(root,'results'); documentationFolder=fullfile(root,'documentation');
if ~isfolder(resultsFolder),mkdir(resultsFolder);end
testPath=fullfile(root,'tests'); addpath(testPath);
pathCleanup=onCleanup(@()rmpath(testPath));

TestResults=run_all_hybrid_bus_tests();
Database=load_hybrid_bus_database(databaseFile);
Input=prepare_hybrid_bus_inputs(Database);
DefaultResult=simulate_hybrid_bus_core(Input);
BaselineComparison=compare_powertrain_concepts(DefaultResult,Input);
Sensitivity=run_hybrid_bus_sensitivity_study(databaseFile);
if options.RunEquivalence
    hybridEquivalence=assess_matlab_simulink_equivalence(databaseFile, ...
        struct('PowertrainMode',"Hybrid"));
    bevEquivalence=assess_matlab_simulink_equivalence(databaseFile, ...
        struct('PowertrainMode',"BEV",'InitialBattery1SOE',0.85, ...
        'InitialBattery2SOE',0.85));
    hybridChecks=addvars(hybridEquivalence.SignalChecks, ...
        repmat("Hybrid",height(hybridEquivalence.SignalChecks),1), ...
        'Before',1,'NewVariableNames','Powertrain');
    bevChecks=addvars(bevEquivalence.SignalChecks, ...
        repmat("BEV",height(bevEquivalence.SignalChecks),1), ...
        'Before',1,'NewVariableNames','Powertrain');
    overallStatus=passFail(hybridEquivalence.OverallStatus=="PASS" && ...
        bevEquivalence.OverallStatus=="PASS");
    Equivalence=struct('OverallStatus',overallStatus, ...
        'SignalChecks',[hybridChecks;bevChecks], ...
        'Note',"Independent Hybrid and BEV implementations are compared. "+ ...
        "Equivalence is not measured-vehicle validation.");
else
    Equivalence=struct('OverallStatus',"NOT RUN",'SignalChecks',table);
end

Traceability=requirementsTraceability(TestResults,Equivalence);
GateSummary=credibilityGates(TestResults,Equivalence,Traceability);
Credibility=struct('GeneratedAt',datetime('now'),'DatabaseVersion',Database.Version, ...
    'GateSummary',GateSummary,'Traceability',Traceability,'TestResults',TestResults, ...
    'Equivalence',Equivalence,'BaselineComparison',BaselineComparison, ...
    'Sensitivity',Sensitivity,'DefaultResultSummary',DefaultResult.Summary);

writetable(GateSummary,fullfile(resultsFolder,'Model_Credibility_Summary.csv'));
writetable(Traceability,fullfile(resultsFolder,'Requirements_Traceability_Matrix.csv'));
writetable(BaselineComparison,fullfile(resultsFolder,'Powertrain_Concept_Comparison.csv'));
writetable(Sensitivity.Results,fullfile(resultsFolder,'Sensitivity_Study.csv'));
if ~isempty(Equivalence.SignalChecks)
    writetable(Equivalence.SignalChecks,fullfile(resultsFolder,'MATLAB_Simulink_Equivalence.csv'));
end
save(fullfile(resultsFolder,'HybridBus_Credibility.mat'),'Credibility','-v7.3');
writeCredibilityMarkdown(Credibility,fullfile(documentationFolder,'Model_Credibility_Report.md'));
writeTraceabilityMarkdown(Traceability,fullfile(documentationFolder,'Requirements_Traceability_Matrix.md'));
writeTestReport(Credibility,fullfile(documentationFolder,'Test_Report.md'));
end

function T=requirementsTraceability(TestResults,Equivalence)
id=["REQ-PHY-001";"REQ-PHY-002";"REQ-DRV-001";"REQ-ENE-001";"REQ-CTL-001"; ...
    "REQ-CTL-002";"REQ-CTL-003";"REQ-BRK-001";"REQ-SAF-001";"REQ-BAT-001";"REQ-DAT-001";"REQ-DAT-002";"REQ-DAT-003";"REQ-DAT-004";"REQ-NUM-001"; ...
    "REQ-OPT-001";"REQ-PERF-001";"REQ-PERF-002";"REQ-PERF-003"; ...
    "REQ-PERF-004";"REQ-PERF-005";"REQ-CON-001";"REQ-CON-002"; ...
    "REQ-CON-003";"REQ-EQV-001"];
category=["Physics";"Physics";"Driveline";"Energy";"Control";"Control"; ...
    "Control";"Braking";"Protection";"Battery";"Data";"Data";"Data";"Data"; ...
    "Numerics";"Optimization";"Performance";"Performance";"Performance"; ...
    "Performance";"Performance";"Constrained performance"; ...
    "Constrained performance";"Constrained performance";"Equivalence"];
requirement=[ ...
    "Wheel demand shall include inertia, rolling, grade, and aerodynamic forces."; ...
    "Auxiliaries shall consume energy at zero vehicle speed."; ...
    "Motor and reduction limits shall report unmet traction demand."; ...
    "The combined DC boundary shall conserve energy within tolerance."; ...
    "Exactly one battery shall be active for traction at a time."; ...
    "The genset shall charge only the standby battery at constant optimum power."; ...
    "Regeneration shall serve auxiliaries, active battery, then load bank."; ...
    "Pneumatic friction brakes shall supply wheel-braking demand beyond regenerative capability."; ...
    "Battery energy and SOE shall remain within configured bounds."; ...
    "Battery charge-current limit, discharge-current limit, and internal resistance shall vary with SOE and temperature; OCV shall vary with SOC and temperature; terminal power capability shall be derived."; ...
    "Route geometry, display elevation, and time histories shall be ordered, finite, and traceable."; ...
    "Every selectable battery and motor shall be sourced from one versioned MATLAB data file."; ...
    "Every selectable genset shall be sourced from one versioned MATLAB file containing its matched engine, generator, fuel map, and efficiency map."; ...
    "Users shall be able to add batteries, motors, and genset assemblies with nonnumeric IDs without changing central application code."; ...
    "Repeated identical inputs shall produce repeatable results."; ...
    "Ranked configurations shall be feasible and sorted by cost per kilometre."; ...
    "Performance mode shall calculate nonnegative achieved speed and monotonically nondecreasing actual distance after component force limits."; ...
    "Grade and auxiliary demand in Performance mode shall be sampled using actual travelled distance."; ...
    "Sustained inability to overcome road load shall terminate as a stalled, incomplete route rather than crediting prescribed-speed completion."; ...
    "Both BEV and Hybrid shall run under the forward formulation while the dispatcher preserves the legacy backward result."; ...
    "The editable forward model shall separate route/terrain, driver/demand, component limits, and vehicle plant into documented subsystems."; ...
    "Constrained mode shall suppress acceleration using battery-current/energy, motor torque-speed/power, final-drive force, and road-load capability."; ...
    "Constrained mode shall use one fixed route-time horizon, actual-distance terrain, and nonnegative speed/distance."; ...
    "Constrained mode shall support BEV and Hybrid and stop a depleted vehicle without rollback."; ...
    "MATLAB and Simulink implementations shall agree within declared tolerances."];
equation=["4.1-4.8";"6.1";"5.1-5.4";"9.1";"8.1";"7.1-7.2"; ...
    "8.1-8.4";"Blended-braking allocation";"6.2-6.4";"Battery lookup maps / first-order Thevenin relation";"3.2";"Data architecture";"Data architecture";"Recursive component discovery / explicit assembly links";"10.1"; ...
    "12.1-12.3";"Forward longitudinal force balance and discrete integration"; ...
    "Distance-domain route lookup";"Stall duration and force-margin rule"; ...
    "Common result contract and formulation dispatcher"; ...
    "HybridBus_PerformanceModel.slx";"Acceleration suppression around backward energy kernel"; ...
    "Fixed route-time integration / distance lookup";"Energy depletion and no-rollback rule"; ...
    "Credibility protocol"];
signal=["Wheel.Demand_kW";"Auxiliary.Power_kW";"Wheel.UnmetTraction_kW"; ...
    "Energy.BalanceResidual_kW";"Controller.ActiveBattery";"Genset.ElectricalPower_kW"; ...
    "Regeneration.*";"Wheel.FrictionBrakePower_kW";"Battery1/2.SOE"; ...
    "Battery1/2 current limits, OCV, derived power capability, resistance, terminal voltage, current, ohmic loss"; ...
    "RouteData / Geometry / Elevation_m";"BatteryData / MotorData";"GensetData";"Component catalogs and dropdowns";"Summary"; ...
    "TopConfigurations";"Vehicle.Speed_m_s / Distance_m"; ...
    "Vehicle.Grade_pct / Distance_m";"Summary.RouteCompleted / TerminationReason"; ...
    "Summary.SimulationFormulation / PowertrainMode";"Simulink subsystem interfaces"; ...
    "Vehicle desired/actual acceleration, force, speed"; ...
    "Vehicle.Distance_m / Grade_pct / Summary.ActualCompletionTime_s"; ...
    "Battery SOE / Vehicle.Speed_m_s / PowertrainMode"; ...
    "Equivalence.SignalChecks"];
test=["ConstantSpeedLevel; LevelAcceleration; PositiveGrade";"StationaryAuxiliary"; ...
    "MotorSaturation";"EnergyConservation";"BatterySwitching"; ...
    "StandbyGensetCharge; GensetTractionIsolation; GensetBestEfficiencyPoint"; ...
    "RegenerationPriority";"PneumaticBrakeBlending";"BatteryUpperLimit; BatteryLowerLimit"; ...
    "BatteryDynamicMaps"; ...
    "RouteGeolocation; RouteValidationFailure; RouteMatStorage";"ComponentMFileStorage";"GensetMFileStorage";"ComponentExtension";"Repeatability; ZeroSpeedStability"; ...
    "OptimizationRanking";"ForwardFlatRoute; ForwardSevereGradeStall"; ...
    "ForwardDistanceIndexedGrade";"ForwardSevereGradeStall"; ...
    "ForwardPowertrainModes; FormulationDispatcher";"ForwardSimulinkStructure"; ...
    "ConstrainedAccelerationSuppression"; ...
    "ConstrainedDistanceTerrain; ConstrainedFixedHorizon"; ...
    "ConstrainedEnergyDepletion; ConstrainedPowertrainModes"; ...
    "MATLAB-Simulink equivalence suite"];
acceptance=["Hand calculation within 2% for constant-speed case";"Positive energy delta and analytical match"; ...
    "Unmet energy is positive when saturated";"Integrated absolute residual below tolerance"; ...
    "Role swap obeys fixed 30% rule";"No traction offset and fixed nonzero genset command"; ...
    "Allocation identity closes and surplus reaches load bank"; ...
    "Braking demand equals regenerative plus pneumatic plus explicitly unmet braking power"; ...
    "No upper or lower bound violation"; ...
    "Cold and high-SOE derating observed; terminal electrical identities close; both SLX models use lookup-driven saturation"; ...
    "One MAT file per route with valid coordinate/elevation bounds, provenance, and strictly ordered sequence"; ...
    "One schema-valid MATLAB file per unique battery and motor ComponentID"; ...
    "One schema-valid, internally matched MATLAB file per unique genset ComponentID"; ...
    "Arbitrary safe IDs load, validate, survive built-in regeneration, and complete a simulation; duplicates are rejected case-insensitively";"Bitwise-identical scalar KPI result"; ...
    "Feasible cases sorted in ascending objective"; ...
    "Capable vehicle completes; limited vehicle never rolls backward"; ...
    "Grade transition occurs at its route distance, independent of startup delay"; ...
    "Severe underpowered grade case reports stall, incomplete route, and no rollback"; ...
    "Both forward modes conserve energy and backward results remain identical"; ...
    "Four documented feature subsystems compile and structural checks pass"; ...
    "Limited case achieves lower acceleration/speed than the capable case"; ...
    "Terrain transition follows actual distance and sample count equals one route pass"; ...
    "Depleted vehicle remains stopped; both powertrains conserve energy"; ...
    "Every signal check passes its declared tolerance"];
status=strings(size(id));
for index=1:numel(id)
    if id(index)=="REQ-EQV-001"
        status(index)=Equivalence.OverallStatus;
    else
        names=split(test(index),'; ');
        rows=ismember(TestResults.Test,names);
        status(index)=passFail(any(rows) && all(TestResults.Status(rows)=="PASS"));
    end
end
T=table(id,category,requirement,equation,signal,test,acceptance,status, ...
    'VariableNames',{'RequirementID','Category','Requirement','EquationReference', ...
    'EvidenceSignal','VerificationTest','AcceptanceCriterion','Status'});
end

function G=credibilityGates(TestResults,Equivalence,Traceability)
gate=["Requirements traceability";"Physics and control verification"; ...
    "MATLAB-Simulink equivalence";"Uncertainty screening";"Concept baseline comparison"; ...
    "Supplier-data calibration";"Measured-vehicle validation";"Forward-facing feasibility"; ...
    "Fast constrained feasibility"; ...
    "Thermal and ageing validation";"Safety and fault analysis"];
forwardTests=["ForwardFlatRoute","ForwardSevereGradeStall", ...
    "ForwardDistanceIndexedGrade","ForwardPowertrainModes", ...
    "FormulationDispatcher","ForwardSimulinkStructure"];
forwardRows=ismember(TestResults.Test,forwardTests);
forwardPass=nnz(forwardRows)==numel(forwardTests) && all(TestResults.Status(forwardRows)=="PASS");
constrainedTests=["ConstrainedAccelerationSuppression","ConstrainedEnergyDepletion", ...
    "ConstrainedDistanceTerrain","ConstrainedPowertrainModes","ConstrainedFixedHorizon"];
constrainedRows=ismember(TestResults.Test,constrainedTests);
constrainedPass=nnz(constrainedRows)==numel(constrainedTests) && ...
    all(TestResults.Status(constrainedRows)=="PASS");
status=[passFail(all(Traceability.Status(1:end-1)=="PASS")); ...
    passFail(all(TestResults.Status=="PASS"));Equivalence.OverallStatus;"PASS";"PASS"; ...
    "NOT AVAILABLE";"NOT AVAILABLE";passFail(forwardPass);passFail(constrainedPass); ...
    "NOT IMPLEMENTED";"NOT IMPLEMENTED"];
evidence=["Requirement-equation-signal-test matrix";sprintf('%d automated behavioral scenarios',height(TestResults)); ...
    "Signal-level independent implementation comparison";"Deterministic one-at-a-time parameter study"; ...
    "Hybrid result plus transparent BEV and diesel screening equations"; ...
    "Synthetic catalog values only";"No CAN/GPS/dynamometer dataset supplied"; ...
    sprintf('%d forward performance and Simulink structure scenarios',nnz(forwardRows)); ...
    sprintf('%d fast constrained acceleration/terrain/depletion scenarios',nnz(constrainedRows)); ...
    "Energy-state model only";"Architecture rules and nominal tests only"];
decision=["Release evidence is traceable";"Concept behavior verified"; ...
    equivalenceDecision(Equivalence.OverallStatus); ...
    "Use ranges for decision robustness, not statistical confidence"; ...
    "Suitable for concept screening, not procurement";"Obtain validated supplier maps"; ...
    "Collect vehicle measurements and define validation tolerances"; ...
    "Use achieved-speed, gradeability, completion, and stall KPIs for concept screening"; ...
    "Use for rapid screening; retain Performance mode for detailed mission closure"; ...
    "Add dynamic battery temperature and degradation states"; ...
    "Perform FMEA/STPA and fault-injection verification"];
G=table(gate,status,evidence,decision,'VariableNames',{'Gate','Status','Evidence','Decision'});
end

function decision=equivalenceDecision(status)
if status=="PASS"
    decision="Independent Hybrid and BEV implementations agree within declared "+ ...
        "tolerances; do not infer measured-vehicle validation";
else
    decision="Resolve numerical differences before claiming implementation equivalence";
end
end

function writeCredibilityMarkdown(C,path)
lines=["# Model Credibility Report";""; ...
    "Generated: "+string(C.GeneratedAt);"Database version: "+string(C.DatabaseVersion);""; ...
    "This report distinguishes verified concept behavior, implementation equivalence, and measured-vehicle validation. A PASS at one level does not imply a PASS at a higher level.";""; ...
    "## Credibility gates";"";markdownTable(C.GateSummary);""; ...
    "## Independent implementation equivalence";"";markdownTable(C.Equivalence.SignalChecks);""; ...
    "## Powertrain concept screening";"";markdownTable(C.BaselineComparison);""; ...
    "## Sensitivity screening";"";markdownTable(C.Sensitivity.Results);""; ...
    "## Interpretation boundary";""; ...
    "The current project is a verified concept energy model. It is not yet calibrated to supplier hardware or validated against measured vehicle telemetry. Screening baselines and sensitivity results support architecture decisions only."];
writelines(lines,path);
end

function writeTraceabilityMarkdown(T,path)
writelines(["# Requirements Traceability Matrix";""; ...
    "Each claim is linked to its governing equation or rule, observable signal, verification test, and acceptance criterion.";"";markdownTable(T)],path);
end

function writeTestReport(C,path)
R=C.DefaultResultSummary;
lines=["# Test Report";"";"Generated: "+string(C.GeneratedAt); ...
    "Environment: MATLAB/Simulink R2025a, Windows";""; ...
    sprintf('Behavioral suite: **%d passed, %d failed**.',sum(C.TestResults.Status=="PASS"),sum(C.TestResults.Status=="FAIL")); ...
    "MATLAB-Simulink equivalence gate: **"+C.Equivalence.OverallStatus+"**.";""; ...
    sprintf('Default case: %.3f km, %.3f L fuel, %.3f kWh grid-equivalent energy, %.4f EUR/km, %.6f kWh unmet energy, %.3g kWh balance error.', ...
    R.RouteDistance_km,R.Fuel_L,R.GridEquivalentEnergy_kWh,R.CostPer_km,R.UnmetTractionEnergy_kWh,R.EnergyBalanceError_kWh); ...
    "";"Machine-readable evidence is stored in the results folder. See Model_Credibility_Report.md and Requirements_Traceability_Matrix.md for the complete decision context."];
writelines(lines,path);
end

function lines=markdownTable(T)
headers=string(T.Properties.VariableNames); lines=strings(height(T)+2,1);
lines(1)="| "+strjoin(headers," | ")+" |";
lines(2)="|"+strjoin(repmat("---",size(headers)),"|")+"|";
for row=1:height(T)
    values=strings(1,width(T));
    for column=1:width(T)
        value=T{row,column};
        if iscell(value),value=value{1};end
        values(column)=string(value);
        values(column)=replace(values(column),"|","/");
    end
    lines(row+2)="| "+strjoin(values," | ")+" |";
end
lines=lines(:);
end

function value=passFail(condition)
if condition,value="PASS";else,value="FAIL";end
end
