function Components=load_genset_m_files(componentFolder)
%LOAD_GENSET_M_FILES Load one complete MATLAB data script per genset assembly.
arguments
    componentFolder (1,1) string
end

assert(isfolder(componentFolder),'HybridBus:GensetFolderMissing', ...
    'Genset component folder does not exist: %s',componentFolder);
listing=dir(fullfile(componentFolder,'**','*.m'));
assert(~isempty(listing),'HybridBus:GensetFilesMissing', ...
    'No genset MATLAB files were found in %s.',componentFolder);

records=cell(numel(listing),1); engines=cell(numel(listing),1);
generators=cell(numel(listing),1); fuelMaps=cell(numel(listing),1);
generatorMaps=cell(numel(listing),1); storageOrder=zeros(numel(listing),1);
assemblyLinks=cell(numel(listing),1); files=strings(numel(listing),1);
for index=1:numel(listing)
    files(index)=fullfile(listing(index).folder,listing(index).name);
    GensetData=[];
    run(files(index));
    required={'SchemaVersion','Genset','Engine','Generator', ...
        'EngineFuelMap','GeneratorEfficiencyMap'};
    assert(isstruct(GensetData) && all(isfield(GensetData,required)), ...
        'HybridBus:GensetMSchema','%s has an invalid GensetData structure.',files(index));
    assert(isstruct(GensetData.Genset) && isscalar(GensetData.Genset) && ...
        isfield(GensetData.Genset,'ComponentID'), ...
        'HybridBus:GensetMSchema','%s has an invalid genset record.',files(index));
    validateRecordID(GensetData.Genset,"genset",files(index));
    validateRecordID(GensetData.Engine,"engine",files(index));
    validateRecordID(GensetData.Generator,"generator",files(index));
    validateMap(GensetData.EngineFuelMap, ...
        {'NormalizedEngineLoad','BSFC_g_kWh'},files(index));
    validateMap(GensetData.GeneratorEfficiencyMap, ...
        {'NormalizedGeneratorLoad','Efficiency'},files(index));
    records{index}=GensetData.Genset; engines{index}=GensetData.Engine;
    generators{index}=GensetData.Generator;
    fuelMaps{index}=tagMap(GensetData.EngineFuelMap,string(GensetData.Genset.ComponentID));
    generatorMaps{index}=tagMap(GensetData.GeneratorEfficiencyMap, ...
        string(GensetData.Genset.ComponentID));
    assemblyLinks{index}=table(string(GensetData.Genset.ComponentID), ...
        string(GensetData.Engine.ComponentID),string(GensetData.Generator.ComponentID), ...
        'VariableNames',{'GensetID','EngineID','GeneratorID'});
    if isfield(GensetData,'StorageOrder') && isscalar(GensetData.StorageOrder) && ...
            isnumeric(GensetData.StorageOrder) && isfinite(GensetData.StorageOrder)
        storageOrder(index)=double(GensetData.StorageOrder);
    else
        storageOrder(index)=100000;
    end
end

componentIDs=string(cellfun(@(record)record.ComponentID,records,'UniformOutput',false));
[~,order]=sortrows(table(storageOrder,lower(componentIDs(:))),[1 2]);
files=files(order);
records=records(order); engines=engines(order); generators=generators(order);
fuelMaps=fuelMaps(order); generatorMaps=generatorMaps(order); assemblyLinks=assemblyLinks(order);
catalog=struct2table(vertcat(records{:}));
assert(numel(unique(lower(string(catalog.ComponentID))))==height(catalog), ...
    'HybridBus:GensetMDuplicate','Genset MATLAB files contain duplicate ComponentID values.');
engineCatalog=struct2table(vertcat(engines{:}));
generatorCatalog=struct2table(vertcat(generators{:}));
assert(numel(unique(lower(string(engineCatalog.ComponentID))))==height(engineCatalog), ...
    'HybridBus:GensetMDuplicate','Genset MATLAB files contain duplicate engine ComponentID values.');
assert(numel(unique(lower(string(generatorCatalog.ComponentID))))==height(generatorCatalog), ...
    'HybridBus:GensetMDuplicate','Genset MATLAB files contain duplicate generator ComponentID values.');
Components=struct('Folder',componentFolder,'Files',files, ...
    'GensetCatalog',catalog, ...
    'EngineCatalog',engineCatalog, ...
    'GeneratorCatalog',generatorCatalog, ...
    'AssemblyCatalog',vertcat(assemblyLinks{:}), ...
    'EngineFuelMap',vertcat(fuelMaps{:}), ...
    'GeneratorEfficiencyMap',vertcat(generatorMaps{:}));
end

function validateRecordID(record,recordType,file)
assert(isstruct(record) && isscalar(record) && isfield(record,'ComponentID'), ...
    'HybridBus:GensetMSchema','%s has an invalid %s record.',file,recordType);
id=string(record.ComponentID);
assert(isscalar(id) && ~ismissing(id) && strlength(id)>0 && ...
    ~isempty(regexp(id,'^[A-Za-z][A-Za-z0-9._-]*$','once')), ...
    'HybridBus:ComponentID', ...
    '%s has invalid %s ComponentID %s. Use letters, digits, dot, underscore, or hyphen.', ...
    file,recordType,id);
end

function validateMap(map,variables,file)
assert(istable(map) && all(ismember(variables,map.Properties.VariableNames)) && ...
    height(map)>=2 && all(all(isfinite(map{:,variables}))), ...
    'HybridBus:GensetMapSchema','%s contains an invalid performance map.',file);
end

function map=tagMap(map,gensetID)
map=addvars(map,repmat(gensetID,height(map),1),'Before',1, ...
    'NewVariableNames','GensetID');
end
