function Components=load_component_m_files(componentFolder,componentType)
%LOAD_COMPONENT_M_FILES Load one MATLAB data script per component.
arguments
    componentFolder (1,1) string
    componentType (1,1) string {mustBeMember(componentType,["Battery","Motor"])}
end

assert(isfolder(componentFolder),'HybridBus:ComponentFolderMissing', ...
    '%s component folder does not exist: %s',componentType,componentFolder);
listing=dir(fullfile(componentFolder,'**','*.m'));
assert(~isempty(listing),'HybridBus:ComponentFilesMissing', ...
    'No %s component MATLAB files were found in %s.',lower(componentType),componentFolder);

records=cell(numel(listing),1); storageOrder=zeros(numel(listing),1);
maps=cell(numel(listing),1);
files=strings(numel(listing),1); expectedVariable=componentType+"Data";
for index=1:numel(listing)
    files(index)=fullfile(listing(index).folder,listing(index).name);
    BatteryData=[]; MotorData=[];
    run(files(index));
    if expectedVariable=="BatteryData"
        data=BatteryData;
    else
        data=MotorData;
    end
    assert(isstruct(data) && all(isfield(data, ...
        {'SchemaVersion','Component'})), ...
        'HybridBus:ComponentMSchema','%s has an invalid %sData structure.', ...
        files(index),componentType);
    assert(isstruct(data.Component) && isscalar(data.Component) && ...
        isfield(data.Component,'ComponentID'), ...
        'HybridBus:ComponentMSchema','%s has an invalid component record.',files(index));
    validateComponentID(data.Component.ComponentID,componentType,files(index));
    if componentType=="Battery"
        mapFields={'SOEBreakpoints','SOCBreakpoints','TemperatureBreakpoints_C', ...
            'MaxDischargeCurrentMap_A','MaxChargeCurrentMap_A', ...
            'OpenCircuitVoltageMap_V','InternalResistanceMap_Ohm','MapBasis'};
        assert(all(isfield(data,mapFields)), ...
            'HybridBus:BatteryMapSchema','%s lacks required dynamic battery maps.',files(index));
        validateBatteryMaps(data,files(index));
        maps{index}=struct('ComponentID',string(data.Component.ComponentID), ...
            'SOEBreakpoints',double(data.SOEBreakpoints), ...
            'SOCBreakpoints',double(data.SOCBreakpoints), ...
            'TemperatureBreakpoints_C',double(data.TemperatureBreakpoints_C), ...
            'MaxDischargeCurrentMap_A',double(data.MaxDischargeCurrentMap_A), ...
            'MaxChargeCurrentMap_A',double(data.MaxChargeCurrentMap_A), ...
            'OpenCircuitVoltageMap_V',double(data.OpenCircuitVoltageMap_V), ...
            'InternalResistanceMap_Ohm',double(data.InternalResistanceMap_Ohm), ...
            'MapBasis',string(data.MapBasis));
    elseif componentType=="Motor"
        mapFields={'TorqueBreakpoints_Nm','SpeedBreakpoints_rpm', ...
            'MotorLossMap_kW','MapBasis'};
        assert(all(isfield(data,mapFields)), ...
            'HybridBus:MotorMapSchema','%s lacks the required motor loss map.',files(index));
        validateMotorLossMap(data,files(index));
        maps{index}=struct('ComponentID',string(data.Component.ComponentID), ...
            'TorqueBreakpoints_Nm',double(data.TorqueBreakpoints_Nm), ...
            'SpeedBreakpoints_rpm',double(data.SpeedBreakpoints_rpm), ...
            'MotorLossMap_kW',double(data.MotorLossMap_kW), ...
            'MapBasis',string(data.MapBasis));
    end
    records{index}=data.Component;
    if isfield(data,'StorageOrder') && isscalar(data.StorageOrder) && ...
            isnumeric(data.StorageOrder) && isfinite(data.StorageOrder)
        storageOrder(index)=double(data.StorageOrder);
    else
        storageOrder(index)=100000;
    end
end

componentIDs=string(cellfun(@(record)record.ComponentID,records,'UniformOutput',false));
[~,order]=sortrows(table(storageOrder,lower(componentIDs(:))),[1 2]);
records=records(order); files=files(order);
catalog=struct2table(vertcat(records{:}));
componentIDs=lower(string(catalog.ComponentID));
if numel(unique(componentIDs))~=height(catalog)
    error('HybridBus:ComponentMDuplicate','%s', ...
        duplicateMessage(componentType,string(catalog.ComponentID),files));
end
Components=struct('Folder',componentFolder,'Files',files,'Catalog',catalog);
if componentType=="Battery" || componentType=="Motor"
    Components.Maps=vertcat(maps{order});
end
end

function validateMotorLossMap(data,file)
torque=double(data.TorqueBreakpoints_Nm(:)');
speed=double(data.SpeedBreakpoints_rpm(:)');
loss=double(data.MotorLossMap_kW);
assert(numel(torque)>=2 && numel(speed)>=2 && torque(1)==0 && speed(1)==0 && ...
    all(diff(torque)>0) && all(diff(speed)>0) && ...
    isequal(size(loss),[numel(speed),numel(torque)]) && ...
    all(isfinite(loss),'all') && all(loss>=0,'all'), ...
    'HybridBus:MotorMapSchema','%s has an invalid torque-speed loss map.',file);
assert(loss(1,1)==0,'HybridBus:MotorMapSchema', ...
    '%s motor loss must be zero at zero torque and zero speed.',file);
end

function message=duplicateMessage(componentType,componentIDs,files)
normalized=lower(componentIDs);
[uniqueIDs,~,groups]=unique(normalized);
counts=accumarray(groups,1);
duplicateIDs=uniqueIDs(counts>1);
details=strings(numel(duplicateIDs),1);
for index=1:numel(duplicateIDs)
    matches=normalized==duplicateIDs(index);
    details(index)=componentIDs(find(matches,1))+" in "+join(files(matches)," and ");
end
message=componentType+" MATLAB files contain duplicate ComponentID values: "+ ...
    join(details,"; ")+". Change Component.ComponentID inside each copied file.";
end

function validateComponentID(id,componentType,file)
id=string(id);
assert(isscalar(id) && ~ismissing(id) && strlength(id)>0 && ...
    ~isempty(regexp(id,'^[A-Za-z][A-Za-z0-9._-]*$','once')), ...
    'HybridBus:ComponentID', ...
    '%s has invalid %s ComponentID %s. Use letters, digits, dot, underscore, or hyphen.', ...
    file,lower(componentType),id);
end

function validateBatteryMaps(data,file)
soe=double(data.SOEBreakpoints(:)'); temperature=double(data.TemperatureBreakpoints_C(:)');
soc=double(data.SOCBreakpoints(:)');
expectedSize=[numel(temperature),numel(soe)];
assert(numel(soe)>=2 && numel(temperature)>=2 && all(diff(soe)>0) && ...
    all(diff(temperature)>0) && all(soe>=0 & soe<=1), ...
    'HybridBus:BatteryMapSchema','%s has invalid SOE or temperature breakpoints.',file);
assert(numel(soc)>=2 && all(diff(soc)>0) && all(soc>=0 & soc<=1) && ...
    size(data.OpenCircuitVoltageMap_V,2)==numel(soc), ...
    'HybridBus:BatteryMapSchema','%s has invalid SOC breakpoints for its OCV map.',file);
mapNames={'MaxDischargeCurrentMap_A','MaxChargeCurrentMap_A', ...
    'OpenCircuitVoltageMap_V','InternalResistanceMap_Ohm'};
for index=1:numel(mapNames)
    map=double(data.(mapNames{index}));
    assert(isequal(size(map),expectedSize) && all(isfinite(map),'all') && ...
        all(map>=0,'all'), ...
        'HybridBus:BatteryMapSchema','%s has an invalid %s.',file,mapNames{index});
end
assert(all(data.InternalResistanceMap_Ohm>0,'all'), ...
    'HybridBus:BatteryMapSchema','%s internal resistance must be positive.',file);
assert(all(data.OpenCircuitVoltageMap_V>data.Component.MinVoltage_V,'all') && ...
    all(data.OpenCircuitVoltageMap_V<data.Component.MaxVoltage_V,'all'), ...
    'HybridBus:BatteryMapSchema', ...
    '%s open-circuit voltage must remain inside the terminal voltage limits.',file);
end
