function Routes=load_route_mat_files(routeFolder)
%LOAD_ROUTE_MAT_FILES Load and combine the per-route MAT-file database.
arguments
    routeFolder (1,1) string
end

assert(isfolder(routeFolder),'HybridBus:RouteFolderMissing', ...
    'Route MAT-file folder does not exist: %s',routeFolder);
listing=dir(fullfile(routeFolder,'*.mat'));
assert(~isempty(listing),'HybridBus:RouteFilesMissing', ...
    'No route MAT files were found in %s.',routeFolder);

records=cell(numel(listing),1); storageOrder=zeros(numel(listing),1);
files=strings(numel(listing),1);
for index=1:numel(listing)
    files(index)=fullfile(listing(index).folder,listing(index).name);
    payload=load(files(index),'RouteData');
    assert(isfield(payload,'RouteData') && isstruct(payload.RouteData), ...
        'HybridBus:RouteMatSchema','%s does not contain a RouteData structure.',files(index));
    route=payload.RouteData;
    required={'SchemaVersion','StorageOrder','Metadata','TimeSpeed', ...
        'DistanceSpeed','Grade','Geometry'};
    assert(all(isfield(route,required)),'HybridBus:RouteMatSchema', ...
        '%s is missing required RouteData fields.',files(index));
    assert(istable(route.Metadata) && height(route.Metadata)==1 && ...
        istable(route.TimeSpeed) && height(route.TimeSpeed)>=2, ...
        'HybridBus:RouteMatSchema','%s has invalid metadata or time data.',files(index));
    routeID=string(route.Metadata.RouteID);
    assert(all(string(route.TimeSpeed.RouteID)==routeID) && ...
        all(string(route.DistanceSpeed.RouteID)==routeID) && ...
        all(string(route.Grade.RouteID)==routeID) && ...
        all(string(route.Geometry.RouteID)==routeID), ...
        'HybridBus:RouteMatIdentity','RouteID content is inconsistent in %s.',files(index));
    records{index}=route; storageOrder(index)=double(route.StorageOrder);
end

[~,order]=sort(storageOrder); records=records(order); files=files(order);
metadata=cellfun(@(route)route.Metadata,records,'UniformOutput',false);
timeSpeed=cellfun(@(route)route.TimeSpeed,records,'UniformOutput',false);
distanceSpeed=cellfun(@(route)route.DistanceSpeed,records,'UniformOutput',false);
grade=cellfun(@(route)route.Grade,records,'UniformOutput',false);
geometry=cellfun(@(route)route.Geometry,records,'UniformOutput',false);
Routes=struct('Folder',routeFolder,'Files',files, ...
    'Catalog',vertcat(metadata{:}), ...
    'TimeSpeed',vertcat(timeSpeed{:}), ...
    'DistanceSpeed',vertcat(distanceSpeed{:}), ...
    'Grade',vertcat(grade{:}), ...
    'Geometry',vertcat(geometry{:}));
assert(numel(unique(Routes.Catalog.RouteID))==height(Routes.Catalog), ...
    'HybridBus:RouteMatDuplicate','Route MAT files contain duplicate RouteID values.');
end
